//! Renders a [`Manifest`](crate::manifest::Manifest) into Rust source: one
//! `pub mod` per Mendix module, one zero-sized `pub struct` per entity
//! implementing `mxrs_ir::EntityMarker`, and one zero-sized `pub struct`
//! per attribute (flat-named `Entity_Attribute` rather than nested in a
//! same-named submodule, since a type and a module can't share a name)
//! implementing `mxrs_ir::AttributeMarker<Entity = Entity>`.

use std::collections::HashSet;
use std::fmt::Write as _;

use crate::manifest::Manifest;
use crate::TypegenError;

pub fn generate(manifest: &Manifest) -> Result<String, TypegenError> {
    let mut out = String::new();
    out.push_str("// @generated by mxrs-typegen — do not edit by hand.\n");
    out.push_str("#![allow(non_camel_case_types, non_snake_case, dead_code)]\n\n");

    let mut seen_modules: HashSet<&str> = HashSet::new();
    for module in &manifest.modules {
        let module_ident = valid_ident(&module.name, "module name")?;
        if !seen_modules.insert(module.name.as_str()) {
            return Err(TypegenError::DuplicateModule(module.name.clone()));
        }

        writeln!(out, "pub mod {module_ident} {{").unwrap();
        let mut seen_entities: HashSet<&str> = HashSet::new();
        for entity in &module.entities {
            let entity_ident = valid_ident(&entity.name, "entity name")?;
            if !seen_entities.insert(entity.name.as_str()) {
                return Err(TypegenError::DuplicateEntity(module.name.clone(), entity.name.clone()));
            }

            writeln!(out, "    pub struct {entity_ident};").unwrap();
            writeln!(out, "    impl mxrs_ir::EntityMarker for {entity_ident} {{").unwrap();
            writeln!(out, "        const MODULE: &'static str = {:?};", module.name).unwrap();
            writeln!(out, "        const NAME: &'static str = {:?};", entity.name).unwrap();
            out.push_str("    }\n");

            let mut seen_attributes: HashSet<&str> = HashSet::new();
            for attribute in &entity.attributes {
                let attr_ident = valid_ident(attribute, "attribute name")?;
                if !seen_attributes.insert(attribute.as_str()) {
                    return Err(TypegenError::DuplicateAttribute(
                        module.name.clone(),
                        entity.name.clone(),
                        attribute.clone(),
                    ));
                }

                let marker_ident = format!("{entity_ident}_{attr_ident}");
                writeln!(out, "    pub struct {marker_ident};").unwrap();
                writeln!(out, "    impl mxrs_ir::AttributeMarker for {marker_ident} {{").unwrap();
                writeln!(out, "        type Entity = {entity_ident};").unwrap();
                writeln!(out, "        const NAME: &'static str = {attribute:?};").unwrap();
                out.push_str("    }\n");
            }
        }
        out.push_str("}\n\n");
    }

    Ok(out)
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for", "if", "impl",
    "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
    "super", "trait", "true", "type", "unsafe", "use", "where", "while", "async", "await", "dyn", "abstract",
    "become", "box", "do", "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

/// Validates `name` is usable verbatim as a Rust identifier — Mendix names
/// are conventionally already PascalCase/no-symbols, so this is a fail-fast
/// check (a clear manifest error) rather than a name-mangling scheme; a
/// name that needs mangling is a signal the manifest itself is wrong.
fn valid_ident(name: &str, context: &str) -> Result<String, TypegenError> {
    let mut chars = name.chars();
    let starts_ok = chars.next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    let rest_ok = chars.all(|c| c.is_ascii_alphanumeric() || c == '_');
    if !starts_ok || !rest_ok || name.is_empty() {
        return Err(TypegenError::InvalidIdentifier(name.to_string(), context.to_string()));
    }
    if RUST_KEYWORDS.contains(&name) {
        return Err(TypegenError::InvalidIdentifier(name.to_string(), context.to_string()));
    }
    Ok(name.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{EntityManifest, ModuleManifest};

    fn sample() -> Manifest {
        Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![
                    EntityManifest { name: "Order".into(), attributes: vec!["Number".into(), "Total".into()] },
                    EntityManifest { name: "Customer".into(), attributes: vec!["Name".into()] },
                ],
            }],
        }
    }

    #[test]
    fn generates_a_struct_and_entity_marker_impl_per_entity() {
        let out = generate(&sample()).unwrap();
        assert!(out.contains("pub mod Sales"));
        assert!(out.contains("pub struct Order;"));
        assert!(out.contains("impl mxrs_ir::EntityMarker for Order"));
        assert!(out.contains(r#"const MODULE: &'static str = "Sales";"#));
        assert!(out.contains(r#"const NAME: &'static str = "Order";"#));
    }

    #[test]
    fn generates_a_flat_named_attribute_marker_per_attribute() {
        let out = generate(&sample()).unwrap();
        assert!(out.contains("pub struct Order_Number;"));
        assert!(out.contains("impl mxrs_ir::AttributeMarker for Order_Number"));
        assert!(out.contains("type Entity = Order;"));
    }

    #[test]
    fn rejects_a_module_name_that_is_not_a_valid_identifier() {
        let manifest = Manifest { modules: vec![ModuleManifest { name: "Sales-Team".into(), entities: vec![] }] };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(err, TypegenError::InvalidIdentifier(name, _) if name == "Sales-Team"));
    }

    #[test]
    fn rejects_a_rust_keyword_as_an_entity_name() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![EntityManifest { name: "type".into(), attributes: vec![] }],
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(err, TypegenError::InvalidIdentifier(name, _) if name == "type"));
    }

    #[test]
    fn rejects_a_duplicate_entity_name_within_a_module() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![
                    EntityManifest { name: "Order".into(), attributes: vec![] },
                    EntityManifest { name: "Order".into(), attributes: vec![] },
                ],
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(err, TypegenError::DuplicateEntity(module, entity) if module == "Sales" && entity == "Order"));
    }

    #[test]
    fn rejects_a_duplicate_attribute_name_within_an_entity() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![EntityManifest { name: "Order".into(), attributes: vec!["Number".into(), "Number".into()] }],
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::DuplicateAttribute(module, entity, attribute)
                if module == "Sales" && entity == "Order" && attribute == "Number"
        ));
    }
}
