//! `#[derive(MxEntity)]` — M8.3: a second ergonomic front end onto the same
//! `mxrs-dsl` builder API `project! {}` (M8.1) already targets, proving the
//! plan's "no separate code path" rule holds under a second syntax: this
//! macro's generated code calls exactly the same `ModuleBuilder::entity`/
//! `EntityBuilder::string`/`.../decimal`/... methods a caller could reach
//! by hand, or that `project! {}` itself expands to.
//!
//! ```
//! # fn main() {
//! use mxrs_macros::MxEntity;
//!
//! #[derive(MxEntity)]
//! struct Order {
//!     #[mx_attribute(kind = "string", default = "A-0000")]
//!     number: String,
//!     #[mx_attribute(kind = "decimal")]
//!     total: String,
//! }
//!
//! let mut project = mxrs_dsl::ProjectBuilder::new("11.12.1");
//! project.module("Sales", |m| {
//!     Order::mx_register(m);
//! });
//! let definition = project.build();
//! let order = &definition.modules[0].entities[0];
//! assert_eq!(order.name, "Order");
//! assert_eq!(order.attributes[0].name.as_deref(), Some("Number"));
//! # }
//! ```
//!
//! Scope of this pass: only entity name (`#[mx_entity(name = "...")]`,
//! defaults to the struct's own name) and per-field attributes
//! (`#[mx_attribute(kind = "...", default = "...")]`, Mendix attribute name
//! defaults to the field name converted to `PascalCase`) — no associations,
//! documentation, or `persistable` yet (`project! {}`'s own grammar has
//! those; this front end doesn't mirror the full set on its first pass,
//! same "narrow now, widen later" pattern used throughout this codebase).
//! Only plain structs with named fields are supported — tuple/unit structs
//! and enums are a clear compile error, not a silent no-op.

use quote::quote;
use syn::spanned::Spanned;

pub fn expand_derive(input: &syn::DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let struct_name = &input.ident;
    let entity_name = parse_mx_entity_name(&input.attrs, struct_name)?;

    let syn::Data::Struct(data) = &input.data else {
        return Err(syn::Error::new_spanned(
            input,
            "MxEntity can only be derived for a struct",
        ));
    };
    let syn::Fields::Named(fields) = &data.fields else {
        return Err(syn::Error::new_spanned(
            &data.fields,
            "MxEntity requires a struct with named fields",
        ));
    };

    let mut attribute_stmts = Vec::with_capacity(fields.named.len());
    for field in &fields.named {
        let field_ident = field
            .ident
            .as_ref()
            .expect("named field always has an ident");
        let Some((kind, default)) = parse_mx_attribute(&field.attrs)? else {
            return Err(syn::Error::new_spanned(
                field,
                "field is missing #[mx_attribute(kind = \"...\")] (every field MxEntity sees needs one)",
            ));
        };
        let method = attribute_kind_method(&kind, field)?;
        let mendix_name = to_pascal_case(&field_ident.to_string());
        attribute_stmts.push(match default {
            Some(expr) => {
                quote! { e.#method(#mendix_name).default_value = Some((#expr).to_string()); }
            }
            None => quote! { e.#method(#mendix_name); },
        });
    }

    Ok(quote! {
        impl #struct_name {
            /// Registers this entity on `m` — generated by `#[derive(MxEntity)]`.
            /// Lowers to exactly the `mxrs-dsl` calls a caller could write by
            /// hand; nothing here is reachable only through the derive.
            pub fn mx_register(m: &mut ::mxrs_dsl::ModuleBuilder) {
                m.entity(#entity_name, |e| {
                    #(#attribute_stmts)*
                });
            }
        }
    })
}

fn parse_mx_entity_name(attrs: &[syn::Attribute], struct_name: &syn::Ident) -> syn::Result<String> {
    for attr in attrs {
        if !attr.path().is_ident("mx_entity") {
            continue;
        }
        let mut name: Option<String> = None;
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("name") {
                let lit: syn::LitStr = meta.value()?.parse()?;
                name = Some(lit.value());
                Ok(())
            } else {
                Err(meta.error("unknown #[mx_entity(...)] key, expected `name`"))
            }
        })?;
        if let Some(name) = name {
            return Ok(name);
        }
    }
    Ok(struct_name.to_string())
}

/// Returns `None` when the field carries no `#[mx_attribute(...)]` at all
/// (the caller turns that into a "missing attribute" error — distinct from
/// a malformed one, which `parse_nested_meta` already reports with its own
/// span-accurate message).
fn parse_mx_attribute(
    attrs: &[syn::Attribute],
) -> syn::Result<Option<(String, Option<syn::Expr>)>> {
    for attr in attrs {
        if !attr.path().is_ident("mx_attribute") {
            continue;
        }
        let mut kind: Option<String> = None;
        let mut default: Option<syn::Expr> = None;
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("kind") {
                let lit: syn::LitStr = meta.value()?.parse()?;
                kind = Some(lit.value());
                Ok(())
            } else if meta.path.is_ident("default") {
                default = Some(meta.value()?.parse()?);
                Ok(())
            } else {
                Err(meta.error("unknown #[mx_attribute(...)] key, expected `kind` or `default`"))
            }
        })?;
        let Some(kind) = kind else {
            return Err(syn::Error::new(
                attr.span(),
                "#[mx_attribute(...)] requires `kind = \"...\"`",
            ));
        };
        return Ok(Some((kind, default)));
    }
    Ok(None)
}

fn attribute_kind_method(kind: &str, field: &syn::Field) -> syn::Result<syn::Ident> {
    let method = match kind {
        "string" => "string",
        "integer" => "integer",
        "long" => "long",
        "decimal" => "decimal",
        "boolean" => "boolean",
        "datetime" => "datetime",
        "autonumber" => "autonumber",
        other => {
            return Err(syn::Error::new_spanned(
                field,
                format!(
                    "unknown attribute kind `{other}` (expected one of: string, integer, long, decimal, boolean, datetime, autonumber)"
                ),
            ))
        }
    };
    Ok(syn::Ident::new(method, field.span()))
}

/// `order_date` -> `OrderDate` — the Mendix attribute-naming convention;
/// override per field with `#[mx_attribute(..., name = "...")]` is not part
/// of this first pass (not needed yet — nothing has asked for a Mendix name
/// that doesn't already round-trip cleanly through this conversion).
fn to_pascal_case(field_name: &str) -> String {
    field_name
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converts_snake_case_field_names_to_pascal_case() {
        assert_eq!(to_pascal_case("number"), "Number");
        assert_eq!(to_pascal_case("order_date"), "OrderDate");
        assert_eq!(to_pascal_case("id"), "Id");
    }
}
