[package]
name = "mxrs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Public facade for Cargo-native Mendix applications built with mxrs."

[lints]
workspace = true

[dependencies]
mxrs-dsl = { path = "../../authoring/mxrs-dsl" }
mxrs-expr = { path = "../../authoring/mxrs-expr" }
mxrs-ir = { path = "../../authoring/mxrs-ir" }
mxrs-macros = { path = "../../authoring/mxrs-macros" }
mxrs-project = { path = "../mxrs-project" }

