[package]
name = "mxrs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Public facade for Cargo-native Mendix applications built with mxrs."

[lints]
workspace = true

[dependencies]
mxrs-dsl = { path = "../../authoring/mxrs-dsl" }
mxrs-expr = { path = "../../authoring/mxrs-expr" }
mxrs-ir = { path = "../../authoring/mxrs-ir" }
mxrs-macros = { path = "../../authoring/mxrs-macros" }
mxrs-materializers = { path = "../../compiler/mxrs-materializers" }
mxrs-oql = { path = "../../compiler/mxrs-oql" }
mxrs-packager = { path = "../mxrs-packager" }
mxrs-project = { path = "../mxrs-project" }
mxrs-runtime = { path = "../mxrs-runtime" }
mxrs-runtime-http = { path = "../mxrs-runtime-http" }
mxrs-semantic = { path = "../../compiler/mxrs-semantic" }
mxrs-scaffold = { path = "../mxrs-scaffold" }
mxrs-writer = { path = "../../writer/mxrs-writer" }
