//! Transactional lifecycle operations over source generated by MXRS.

use std::path::{Path, PathBuf};

use crate::transaction::Transaction;
use crate::{Result, ScaffoldError, io_error};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectLayout {
    PreLayered,
    /// The layered tree that put every Mendix module in a folder of its own
    /// under `src/modules/`. Recognized so a command can say so instead of
    /// reporting the project as unrecognizable, but nothing writes it any
    /// more: re-import to get the layer-first tree.
    ModuleFirst,
    Layered,
    Incomplete,
}

impl ProjectLayout {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::PreLayered => "pre-layered",
            Self::ModuleFirst => "module-first",
            Self::Layered => "layered",
            Self::Incomplete => "incomplete",
        }
    }
}

impl std::fmt::Display for ProjectLayout {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpgradeReport {
    pub root: PathBuf,
    pub from: String,
    pub to: String,
    pub created: Vec<PathBuf>,
    pub updated: Vec<PathBuf>,
    pub files: Vec<PathBuf>,
    pub migrated_layers: bool,
    pub applied: bool,
}

/// Migrates the generated source layout without changing the Mendix version.
///
/// This is the actionable path for projects created before application and
/// presentation became first-class layers. It deliberately delegates to the
/// same transaction as a version upgrade, so preview and apply have identical
/// safety guarantees.
pub fn migrate_project_layers(target: impl AsRef<Path>, apply: bool) -> Result<UpgradeReport> {
    let target = target.as_ref();
    let root = std::path::absolute(target).map_err(|error| io_error(target, error))?;
    let library = root.join("src/lib.rs");
    let source = std::fs::read_to_string(&library).map_err(|error| io_error(&library, error))?;
    let version = application_version(&source).ok_or(ScaffoldError::MissingVersionDeclaration)?;
    upgrade_project(root, &version, apply)
}

pub fn upgrade_project(
    target: impl AsRef<Path>,
    version: &str,
    apply: bool,
) -> Result<UpgradeReport> {
    validate_version(version)?;
    let target = target.as_ref();
    let root = std::path::absolute(target).map_err(|error| io_error(target, error))?;
    for relative in ["Cargo.toml", "src/lib.rs", "src/domain/mod.rs"] {
        if !root.join(relative).is_file() {
            return Err(ScaffoldError::ProjectNotFound(
                root.join(relative).display().to_string(),
            ));
        }
    }

    let library = root.join("src/lib.rs");
    let library_source =
        std::fs::read_to_string(&library).map_err(|error| io_error(&library, error))?;
    let from =
        application_version(&library_source).ok_or(ScaffoldError::MissingVersionDeclaration)?;
    let mut declarations = vec![format!("src/lib.rs={from}")];
    if let Some(manifest_version) = manifest_version(&root.join("mxrs.toml"))? {
        declarations.push(format!("mxrs.toml={manifest_version}"));
        if manifest_version != from {
            return Err(ScaffoldError::VersionMismatch(declarations));
        }
    }

    let mut transaction = Transaction::default();
    let updated_library = replace_application_version(&library_source, &from, version)
        .ok_or(ScaffoldError::MissingVersionDeclaration)?;
    transaction.write(&library, updated_library)?;

    let migrated_layers = stage_layer_migration(&mut transaction, &root)?;

    let manifest = root.join("mxrs.toml");
    if manifest.is_file() {
        let source =
            std::fs::read_to_string(&manifest).map_err(|error| io_error(&manifest, error))?;
        transaction.write(&manifest, replace_manifest_version(&source, &from, version))?;
    }
    for relative in [
        "src/domain/mod.rs",
        "src/domain/entities/mod.rs",
        "src/domain/documents/mod.rs",
        "src/application/microflows/mod.rs",
        "src/presentation/nanoflows/mod.rs",
        // Kept for projects imported before the application/presentation
        // split. Upgrade is deliberately backward compatible with generated
        // source already under version control.
        "src/domain/flows/mod.rs",
    ] {
        let path = root.join(relative);
        if !path.is_file() {
            continue;
        }
        let source = std::fs::read_to_string(&path).map_err(|error| io_error(&path, error))?;
        transaction.write(&path, replace_builder_versions(&source, &from, version))?;
    }
    let created = transaction.created().to_vec();
    let updated = transaction.updated().to_vec();
    let mut files = created.clone();
    files.extend_from_slice(&updated);
    files.sort();
    if apply {
        transaction.commit()?;
    }
    Ok(UpgradeReport {
        root,
        from,
        to: version.to_string(),
        created,
        updated,
        files,
        migrated_layers,
        applied: apply,
    })
}

/// The layers a migrated pre-layered project gains. Such a project builds
/// its model by hand in `domain::build`, so the migration composes that
/// entry point explicitly instead of moving the user's source into
/// self-registering declarations.
const MIGRATED_APPLICATION_LAYER: &str =
    "pub fn build() -> mxrs::ProjectDecl {\n    crate::domain::build()\n}\n";
const MIGRATED_PRESENTATION_LAYER: &str = "pub fn apply(_project: &mut mxrs::ProjectDecl) {}\n";

fn stage_layer_migration(transaction: &mut Transaction, root: &Path) -> Result<bool> {
    let library = root.join("src/lib.rs");
    let source = transaction
        .content(&library)?
        .ok_or_else(|| ScaffoldError::ProjectNotFound(library.display().to_string()))?;
    match layout_from(root, &source) {
        ProjectLayout::Layered => return Ok(false),
        ProjectLayout::PreLayered => {}
        // Moving a module-first tree means moving the user's own source
        // between folders, and guessing which of it was hand-edited. The
        // importer already produces the layer-first tree from the model, so
        // re-importing is the honest path and this refuses instead.
        ProjectLayout::ModuleFirst | ProjectLayout::Incomplete => {
            return Err(ScaffoldError::UnsupportedLayerMigration(
                root.display().to_string(),
            ));
        }
    }

    transaction.write(&library, layered_library(&source, &library)?)?;
    let application = root.join("src/application/mod.rs");
    let presentation = root.join("src/presentation/mod.rs");
    transaction.create(&application, MIGRATED_APPLICATION_LAYER.to_string())?;
    transaction.create(&presentation, MIGRATED_PRESENTATION_LAYER.to_string())?;

    let infrastructure = root.join("src/infrastructure/mod.rs");
    if transaction.content(&infrastructure)?.is_none() {
        transaction.create(infrastructure, crate::templates::infrastructure_layer())?;
    }
    Ok(true)
}

pub fn project_layout(root: impl AsRef<Path>) -> Result<ProjectLayout> {
    let root = root.as_ref();
    let library = root.join("src/lib.rs");
    let source = match std::fs::read_to_string(&library) {
        Ok(source) => source,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(ProjectLayout::Incomplete);
        }
        Err(error) => return Err(io_error(&library, error)),
    };
    Ok(layout_from(root, &source))
}

fn layout_from(root: &Path, library: &str) -> ProjectLayout {
    let application = root.join("src/application/mod.rs").is_file();
    let presentation = root.join("src/presentation/mod.rs").is_file();
    match (application, presentation) {
        (false, false)
            if library
                .lines()
                .any(|line| matches!(line.trim(), "mod domain;" | "pub mod domain;")) =>
        {
            ProjectLayout::PreLayered
        }
        (true, true) if complete_layered_layout(root, library) => {
            // A `src/modules/` tree is the earlier layered shape. Naming it is
            // what keeps the diagnostic honest: the module is there, the
            // layout moved.
            if root.join("src/modules/mod.rs").is_file() {
                ProjectLayout::ModuleFirst
            } else {
                ProjectLayout::Layered
            }
        }
        _ => ProjectLayout::Incomplete,
    }
}

fn complete_layered_layout(root: &Path, library: &str) -> bool {
    ["src/domain/mod.rs", "src/infrastructure/mod.rs"]
        .iter()
        .all(|relative| root.join(relative).is_file())
        && [
            "pub mod application;",
            "pub mod domain;",
            "pub mod infrastructure;",
            "pub mod presentation;",
        ]
        .iter()
        .all(|declaration| library.lines().any(|line| line.trim() == *declaration))
        // The application either registers its declarations — the shape
        // `mxrs new` and the importer write — or names the entry point that
        // composes them; both are complete.
        && crate::artifact::rust_application_metadata(library)
            .is_ok_and(|(version, _)| version.is_some())
}

fn layered_library(source: &str, path: &Path) -> Result<String> {
    let mut lines = Vec::new();
    let mut inserted_layers = false;
    let mut found_domain = false;
    for line in source.lines() {
        let declaration = line.trim();
        let is_layer = matches!(
            declaration,
            "mod application;"
                | "pub mod application;"
                | "mod domain;"
                | "pub mod domain;"
                | "mod infrastructure;"
                | "pub mod infrastructure;"
                | "mod modules;"
                | "pub mod modules;"
                | "mod presentation;"
                | "pub mod presentation;"
        );
        if matches!(declaration, "mod domain;" | "pub mod domain;") {
            found_domain = true;
        }
        if is_layer {
            if !inserted_layers {
                lines.extend(
                    [
                        "pub mod application;",
                        "pub mod domain;",
                        "pub mod infrastructure;",
                        "pub mod presentation;",
                    ]
                    .map(str::to_string),
                );
                inserted_layers = true;
            }
        } else {
            lines.push(line.to_string());
        }
    }
    if !found_domain || !inserted_layers {
        return Err(ScaffoldError::UnsupportedLayerMigration(
            path.display().to_string(),
        ));
    }

    let attribute = lines
        .iter()
        .position(|line| application_version_on_line(line).is_some())
        .ok_or(ScaffoldError::MissingVersionDeclaration)?;
    if lines[attribute].contains("project =") || lines.iter().any(|line| line.contains("fn build("))
    {
        return Err(ScaffoldError::UnsupportedLayerMigration(
            path.display().to_string(),
        ));
    }
    let Some(end) = lines[attribute].rfind(")]") else {
        return Err(ScaffoldError::UnsupportedLayerMigration(
            path.display().to_string(),
        ));
    };
    lines[attribute].insert_str(end, ", project = crate::build");
    let composition = [
        "pub fn build() -> mxrs::ProjectDecl {",
        "    let mut project = application::build();",
        "    presentation::apply(&mut project);",
        "    project",
        "}",
        "",
    ];
    lines.splice(attribute..attribute, composition.map(str::to_string));
    Ok(join_lines(lines))
}

fn join_lines(lines: Vec<String>) -> String {
    let mut source = lines.join("\n");
    source.push('\n');
    source
}

fn validate_version(version: &str) -> Result<()> {
    let parts = version.split('.').collect::<Vec<_>>();
    if !(3..=4).contains(&parts.len())
        || parts.iter().any(|part| {
            part.is_empty()
                || !part.bytes().all(|byte| byte.is_ascii_digit())
                || part.parse::<u32>().is_err()
        })
    {
        return Err(ScaffoldError::InvalidVersion(version.to_string()));
    }
    Ok(())
}

fn application_version(source: &str) -> Option<String> {
    source.lines().find_map(application_version_on_line)
}

fn application_version_on_line(line: &str) -> Option<String> {
    let value = line
        .trim()
        .strip_prefix("#[mxrs::application(version =")?
        .trim();
    quoted(value)
}

fn manifest_version(path: &Path) -> Result<Option<String>> {
    let source = match std::fs::read_to_string(path) {
        Ok(source) => source,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(io_error(path, error)),
    };
    Ok(source.lines().find_map(|line| {
        let value = line.trim().strip_prefix("mendix_version")?.trim();
        quoted(value.strip_prefix('=')?.trim())
    }))
}

fn quoted(value: &str) -> Option<String> {
    let value = value.strip_prefix('"')?;
    Some(value[..value.find('"')?].to_string())
}

fn replace_application_version(source: &str, from: &str, to: &str) -> Option<String> {
    let needle = format!("version = \"{from}\"");
    let replacement = format!("version = \"{to}\"");
    let mut replaced = false;
    let updated = source
        .split_inclusive('\n')
        .map(|line| {
            if !replaced && application_version_on_line(line).as_deref() == Some(from) {
                replaced = true;
                line.replacen(&needle, &replacement, 1)
            } else {
                line.to_string()
            }
        })
        .collect();
    replaced.then_some(updated)
}

fn replace_manifest_version(source: &str, from: &str, to: &str) -> String {
    let mut replaced = false;
    source
        .split_inclusive('\n')
        .map(|line| {
            if !replaced
                && line
                    .trim()
                    .strip_prefix("mendix_version")
                    .and_then(|value| value.trim().strip_prefix('='))
                    .and_then(|value| quoted(value.trim()))
                    .as_deref()
                    == Some(from)
            {
                replaced = true;
                let start = line.find('"').expect("parsed quoted value");
                let end = start + 1 + line[start + 1..].find('"').expect("parsed closing quote");
                format!("{}{}{}", &line[..start + 1], to, &line[end..])
            } else {
                line.to_string()
            }
        })
        .collect()
}

fn replace_builder_versions(source: &str, from: &str, to: &str) -> String {
    let needle = format!("ProjectBuilder::new(\"{from}\")");
    source.replace(&needle, &format!("ProjectBuilder::new(\"{to}\")"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(root: &Path, relative: &str, body: &str) {
        let path = root.join(relative);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, body).unwrap();
    }

    fn layered_shell(root: &Path) {
        for (relative, body) in [
            ("Cargo.toml", "[package]\nname = \"app\"\n"),
            (
                "src/lib.rs",
                concat!(
                    "pub mod application;\n",
                    "pub mod domain;\n",
                    "pub mod infrastructure;\n",
                    "pub mod presentation;\n\n",
                    "pub fn build() {}\n\n",
                    "#[mxrs::application(version = \"11.12.1\", ",
                    "project = crate::build)]\npub struct Application;\n"
                ),
            ),
            ("src/domain/mod.rs", "pub fn build() {}\n"),
            ("src/application/mod.rs", ""),
            ("src/infrastructure/mod.rs", ""),
            ("src/presentation/mod.rs", ""),
        ] {
            write(root, relative, body);
        }
    }

    fn pre_layered_shell(root: &Path, infrastructure: bool) -> (String, Option<String>) {
        let domain = concat!(
            "pub fn build() -> mxrs::ProjectDecl {\n",
            "    let mut project = mxrs::ProjectBuilder::new(\"11.12.1\");\n",
            "    project.module(\"Main\", |_module| {});\n",
            "    project.build()\n",
            "}\n"
        )
        .to_string();
        write(root, "Cargo.toml", "[package]\nname = \"app\"\n");
        write(
            root,
            "src/lib.rs",
            concat!(
                "mod domain;\n\n",
                "#[mxrs::application(version = \"11.12.1\")]\n",
                "pub struct Application;\n"
            ),
        );
        write(root, "src/domain/mod.rs", &domain);
        let infrastructure = infrastructure.then(|| {
            let source = "//! Existing integration code.\n".to_string();
            write(root, "src/infrastructure/mod.rs", &source);
            source
        });
        (domain, infrastructure)
    }

    #[test]
    fn preview_is_read_only_and_apply_updates_only_generated_version_markers() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        crate::generate_project(&crate::ProjectScaffold::new("App", "11.12.1", &root)).unwrap();
        // A fresh project states its version once, on the application. A
        // project that also composes part of its model by hand restates it
        // on each builder, and those follow the upgrade too — while a
        // version-shaped literal that is *not* a `ProjectBuilder::new`
        // argument survives untouched.
        let domain = root.join("src/domain/mod.rs");
        let mut source = std::fs::read_to_string(&domain).unwrap();
        source.push_str(
            "\npub fn composed() -> mxrs::ProjectDecl {\n    let mut builder = mxrs::ProjectBuilder::new(\"11.12.1\");\n    builder.module(\"literal 11.12.1 must stay\", |_module| {});\n    builder.build()\n}\n",
        );
        std::fs::write(&domain, source).unwrap();

        let preview = upgrade_project(&root, "11.13.0", false).unwrap();
        assert!(!preview.applied);
        assert!(!preview.migrated_layers);
        assert_eq!(preview.files.len(), 2);
        assert!(
            std::fs::read_to_string(root.join("src/lib.rs"))
                .unwrap()
                .contains("11.12.1")
        );

        let applied = upgrade_project(&root, "11.13.0", true).unwrap();
        assert!(applied.applied);
        assert!(
            std::fs::read_to_string(root.join("src/lib.rs"))
                .unwrap()
                .contains("11.13.0")
        );
        let domain = std::fs::read_to_string(domain).unwrap();
        assert!(domain.contains("ProjectBuilder::new(\"11.13.0\")"));
        assert!(domain.contains("literal 11.12.1 must stay"));
    }

    #[test]
    fn invalid_and_inconsistent_versions_fail_closed() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        crate::generate_project(&crate::ProjectScaffold::new("App", "11.12.1", &root)).unwrap();
        assert!(matches!(
            upgrade_project(&root, "next", false),
            Err(ScaffoldError::InvalidVersion(_))
        ));
        std::fs::write(
            root.join("mxrs.toml"),
            "[project]\nmendix_version = \"10.0.0\"\n",
        )
        .unwrap();
        assert!(matches!(
            upgrade_project(&root, "11.13.0", false),
            Err(ScaffoldError::VersionMismatch(_))
        ));
    }

    /// Both generators now declare `project = crate::build` next to the
    /// version. Upgrading must still find and rewrite the version without
    /// disturbing the composition root the attribute names, and must keep
    /// working for a project that names a deeper entry point by hand.
    #[test]
    fn application_attribute_keeps_its_project_entry_point_across_an_upgrade() {
        for entry_point in ["crate::build", "crate::application::build"] {
            let source = format!(
                "#[mxrs::application(version = \"11.12.1\", project = {entry_point})]\npub struct Application;\n"
            );
            assert_eq!(application_version(&source).as_deref(), Some("11.12.1"));
            assert_eq!(
                replace_application_version(&source, "11.12.1", "11.13.0").as_deref(),
                Some(
                    format!(
                        "#[mxrs::application(version = \"11.13.0\", project = {entry_point})]\npub struct Application;\n"
                    )
                    .as_str()
                )
            );
        }
    }

    /// The version-only attribute `mxrs new` emitted before the layering
    /// increment must keep upgrading, since it is still what every project
    /// already under version control declares.
    #[test]
    fn version_only_application_attribute_still_upgrades() {
        let source = "#[mxrs::application(version = \"11.12.1\")]\npub struct Application;\n";
        assert_eq!(application_version(source).as_deref(), Some("11.12.1"));
        assert_eq!(
            replace_application_version(source, "11.12.1", "11.13.0").as_deref(),
            Some("#[mxrs::application(version = \"11.13.0\")]\npub struct Application;\n")
        );
    }

    /// The layered layout and the pre-split one both exist in the wild, so an
    /// upgrade has to rewrite whichever flow modules a project actually has
    /// and leave the version literal alone everywhere else.
    #[test]
    fn upgrade_rewrites_layered_and_pre_split_flow_modules() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        layered_shell(&root);
        let builder = "fn declarations() {\n    ::mxrs_dsl::ProjectBuilder::new(\"11.12.1\");\n}\n";
        for (relative, body) in [
            ("src/application/microflows/mod.rs", builder),
            ("src/presentation/nanoflows/mod.rs", builder),
            ("src/domain/flows/mod.rs", builder),
        ] {
            write(&root, relative, body);
        }

        let report = upgrade_project(&root, "11.13.0", true).unwrap();
        assert_eq!(report.from, "11.12.1");
        // `src/domain/mod.rs` carries no version literal, so it is not an
        // update — the transaction reports only the four files it rewrote.
        assert_eq!(report.files.len(), 4);
        for relative in [
            "src/application/microflows/mod.rs",
            "src/presentation/nanoflows/mod.rs",
            "src/domain/flows/mod.rs",
        ] {
            let source = std::fs::read_to_string(root.join(relative)).unwrap();
            assert!(
                source.contains("ProjectBuilder::new(\"11.13.0\")"),
                "{relative} kept the old version"
            );
        }
        let library = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
        assert!(library.contains("version = \"11.13.0\""));
        assert!(library.contains("project = crate::build"));
    }

    /// `src/domain/documents/mod.rs` opens its `declarations()` with the same
    /// `ProjectBuilder::new("<version>")` call the flow modules use, so leaving
    /// it out of the upgrade would strand one generated file on the old version
    /// while its siblings moved — a difference nothing else in the project
    /// would surface.
    #[test]
    fn upgrade_rewrites_the_imported_documents_module_too() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        layered_shell(&root);
        let documents = concat!(
            "//! Editable Cargo-native enumerations, constants, regular expressions, ",
            "scheduled events, and menus.\n\n",
            "fn declarations() -> ::mxrs_ir::ProjectDecl {\n",
            "    let mut project = ::mxrs_dsl::ProjectBuilder::new(\"11.12.1\");\n",
            "    project.module(\"Sales\", |module| {\n",
            "        module.constant(\"ReleaseNote\", |constant| {\n",
            // A version-shaped literal that is not a builder argument must
            // survive, the same way it does in `src/domain/mod.rs`.
            "            constant.value(\"pinned to 11.12.1\");\n",
            "        });\n",
            "    });\n",
            "    project.build()\n}\n",
        );
        write(&root, "src/domain/documents/mod.rs", documents);

        let report = upgrade_project(&root, "11.13.0", true).unwrap();
        assert_eq!(report.from, "11.12.1");
        assert!(
            report
                .files
                .iter()
                .any(|file| file.ends_with("src/domain/documents/mod.rs")),
            "the documents module was not reported as updated: {:?}",
            report.files
        );
        let updated = std::fs::read_to_string(root.join("src/domain/documents/mod.rs")).unwrap();
        assert!(updated.contains("ProjectBuilder::new(\"11.13.0\")"));
        assert!(!updated.contains("ProjectBuilder::new(\"11.12.1\")"));
        assert!(updated.contains("pinned to 11.12.1"));
    }

    #[test]
    fn pre_layered_migration_previews_applies_preserves_and_is_idempotent() {
        for keep_infrastructure in [false, true] {
            let directory = tempfile::tempdir().unwrap();
            let root = directory.path().join("app");
            let (domain, infrastructure) = pre_layered_shell(&root, keep_infrastructure);
            let library = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
            assert_eq!(project_layout(&root).unwrap(), ProjectLayout::PreLayered);

            let preview = migrate_project_layers(&root, false).unwrap();
            assert!(preview.migrated_layers);
            assert!(!preview.applied);
            assert_eq!(preview.from, preview.to);
            assert!(
                preview
                    .updated
                    .iter()
                    .any(|path| path.ends_with("src/lib.rs"))
            );
            assert!(!root.join("src/application/mod.rs").exists());
            assert_eq!(
                std::fs::read_to_string(root.join("src/lib.rs")).unwrap(),
                library
            );

            let applied = migrate_project_layers(&root, true).unwrap();
            assert!(applied.migrated_layers);
            assert!(applied.applied);
            for relative in [
                "src/application/mod.rs",
                "src/presentation/mod.rs",
                "src/infrastructure/mod.rs",
            ] {
                assert!(root.join(relative).is_file(), "missing {relative}");
            }
            // Migration creates the layers, never a module tree.
            assert!(!root.join("src/modules").exists());
            assert_eq!(
                std::fs::read_to_string(root.join("src/domain/mod.rs")).unwrap(),
                domain
            );
            if let Some(infrastructure) = infrastructure {
                assert_eq!(
                    std::fs::read_to_string(root.join("src/infrastructure/mod.rs")).unwrap(),
                    infrastructure
                );
                assert!(
                    !applied
                        .created
                        .iter()
                        .any(|path| path.ends_with("src/infrastructure/mod.rs"))
                );
            } else {
                assert!(
                    applied
                        .created
                        .iter()
                        .any(|path| path.ends_with("src/infrastructure/mod.rs"))
                );
            }
            let library = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
            for declaration in [
                "pub mod application;",
                "pub mod domain;",
                "pub mod infrastructure;",
                "pub mod presentation;",
                "project = crate::build",
                "let mut project = application::build();",
                "presentation::apply(&mut project);",
            ] {
                assert!(library.contains(declaration), "{declaration}: {library}");
            }
            assert_eq!(project_layout(&root).unwrap(), ProjectLayout::Layered);

            let repeated = migrate_project_layers(&root, true).unwrap();
            assert!(!repeated.migrated_layers);
            assert!(repeated.files.is_empty());
            assert!(repeated.created.is_empty());
            assert!(repeated.updated.is_empty());
        }
    }

    #[test]
    fn incomplete_or_custom_layouts_fail_without_publishing_staged_changes() {
        for partial_shape in ["one-layer", "missing-aggregators", "custom-entry-point"] {
            let directory = tempfile::tempdir().unwrap();
            let root = directory.path().join("app");
            let (domain, _) = pre_layered_shell(&root, false);
            match partial_shape {
                "one-layer" => write(&root, "src/application/mod.rs", "pub mod modules;\n"),
                "missing-aggregators" => {
                    write(&root, "src/application/mod.rs", "pub mod modules;\n");
                    write(&root, "src/presentation/mod.rs", "pub mod modules;\n");
                }
                "custom-entry-point" => {
                    let path = root.join("src/lib.rs");
                    let source = std::fs::read_to_string(&path)
                        .unwrap()
                        .replace(")]", ", project = crate::domain::build)]");
                    std::fs::write(path, source).unwrap();
                }
                _ => unreachable!(),
            }
            let library = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
            assert!(matches!(
                upgrade_project(&root, "11.13.0", true),
                Err(ScaffoldError::UnsupportedLayerMigration(_))
            ));
            assert_eq!(
                std::fs::read_to_string(root.join("src/lib.rs")).unwrap(),
                library
            );
            assert_eq!(
                std::fs::read_to_string(root.join("src/domain/mod.rs")).unwrap(),
                domain
            );
            assert!(!root.join("src/modules/mod.rs").exists());
        }
    }

    #[test]
    fn compact_manifest_syntax_is_updated_instead_of_silently_skipped() {
        let source = "[project]\n  mendix_version=\"11.12.1\"\nname = \"App\"\n";
        assert_eq!(
            replace_manifest_version(source, "11.12.1", "11.13.0"),
            "[project]\n  mendix_version=\"11.13.0\"\nname = \"App\"\n"
        );
    }
}
