//! Transactional lifecycle operations over source generated by MXRS.

use std::path::{Path, PathBuf};

use crate::transaction::Transaction;
use crate::{Result, ScaffoldError, io_error};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpgradeReport {
    pub root: PathBuf,
    pub from: String,
    pub to: String,
    pub files: Vec<PathBuf>,
    pub applied: bool,
}

pub fn upgrade_project(
    target: impl AsRef<Path>,
    version: &str,
    apply: bool,
) -> Result<UpgradeReport> {
    validate_version(version)?;
    let target = target.as_ref();
    let root = std::path::absolute(target).map_err(|error| io_error(target, error))?;
    for relative in ["Cargo.toml", "src/lib.rs", "src/domain/mod.rs"] {
        if !root.join(relative).is_file() {
            return Err(ScaffoldError::ProjectNotFound(
                root.join(relative).display().to_string(),
            ));
        }
    }

    let library = root.join("src/lib.rs");
    let library_source =
        std::fs::read_to_string(&library).map_err(|error| io_error(&library, error))?;
    let from =
        application_version(&library_source).ok_or(ScaffoldError::MissingVersionDeclaration)?;
    let mut declarations = vec![format!("src/lib.rs={from}")];
    if let Some(manifest_version) = manifest_version(&root.join("mxrs.toml"))? {
        declarations.push(format!("mxrs.toml={manifest_version}"));
        if manifest_version != from {
            return Err(ScaffoldError::VersionMismatch(declarations));
        }
    }

    let mut transaction = Transaction::default();
    let updated_library = replace_application_version(&library_source, &from, version)
        .ok_or(ScaffoldError::MissingVersionDeclaration)?;
    transaction.write(&library, updated_library)?;

    let manifest = root.join("mxrs.toml");
    if manifest.is_file() {
        let source =
            std::fs::read_to_string(&manifest).map_err(|error| io_error(&manifest, error))?;
        transaction.write(&manifest, replace_manifest_version(&source, &from, version))?;
    }
    for relative in [
        "src/domain/mod.rs",
        "src/domain/entities/mod.rs",
        "src/domain/documents/mod.rs",
        "src/application/microflows/mod.rs",
        "src/presentation/nanoflows/mod.rs",
        // Kept for projects imported before the application/presentation
        // split. Upgrade is deliberately backward compatible with generated
        // source already under version control.
        "src/domain/flows/mod.rs",
    ] {
        let path = root.join(relative);
        if !path.is_file() {
            continue;
        }
        let source = std::fs::read_to_string(&path).map_err(|error| io_error(&path, error))?;
        transaction.write(&path, replace_builder_versions(&source, &from, version))?;
    }
    let files = transaction.updated().to_vec();
    if apply {
        transaction.commit()?;
    }
    Ok(UpgradeReport {
        root,
        from,
        to: version.to_string(),
        files,
        applied: apply,
    })
}

fn validate_version(version: &str) -> Result<()> {
    let parts = version.split('.').collect::<Vec<_>>();
    if !(3..=4).contains(&parts.len())
        || parts.iter().any(|part| {
            part.is_empty()
                || !part.bytes().all(|byte| byte.is_ascii_digit())
                || part.parse::<u32>().is_err()
        })
    {
        return Err(ScaffoldError::InvalidVersion(version.to_string()));
    }
    Ok(())
}

fn application_version(source: &str) -> Option<String> {
    source.lines().find_map(application_version_on_line)
}

fn application_version_on_line(line: &str) -> Option<String> {
    let value = line
        .trim()
        .strip_prefix("#[mxrs::application(version =")?
        .trim();
    quoted(value)
}

fn manifest_version(path: &Path) -> Result<Option<String>> {
    let source = match std::fs::read_to_string(path) {
        Ok(source) => source,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(io_error(path, error)),
    };
    Ok(source.lines().find_map(|line| {
        let value = line.trim().strip_prefix("mendix_version")?.trim();
        quoted(value.strip_prefix('=')?.trim())
    }))
}

fn quoted(value: &str) -> Option<String> {
    let value = value.strip_prefix('"')?;
    Some(value[..value.find('"')?].to_string())
}

fn replace_application_version(source: &str, from: &str, to: &str) -> Option<String> {
    let needle = format!("version = \"{from}\"");
    let replacement = format!("version = \"{to}\"");
    let mut replaced = false;
    let updated = source
        .split_inclusive('\n')
        .map(|line| {
            if !replaced && application_version_on_line(line).as_deref() == Some(from) {
                replaced = true;
                line.replacen(&needle, &replacement, 1)
            } else {
                line.to_string()
            }
        })
        .collect();
    replaced.then_some(updated)
}

fn replace_manifest_version(source: &str, from: &str, to: &str) -> String {
    let mut replaced = false;
    source
        .split_inclusive('\n')
        .map(|line| {
            if !replaced
                && line
                    .trim()
                    .strip_prefix("mendix_version")
                    .and_then(|value| value.trim().strip_prefix('='))
                    .and_then(|value| quoted(value.trim()))
                    .as_deref()
                    == Some(from)
            {
                replaced = true;
                let start = line.find('"').expect("parsed quoted value");
                let end = start + 1 + line[start + 1..].find('"').expect("parsed closing quote");
                format!("{}{}{}", &line[..start + 1], to, &line[end..])
            } else {
                line.to_string()
            }
        })
        .collect()
}

fn replace_builder_versions(source: &str, from: &str, to: &str) -> String {
    let needle = format!("ProjectBuilder::new(\"{from}\")");
    source.replace(&needle, &format!("ProjectBuilder::new(\"{to}\")"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preview_is_read_only_and_apply_updates_only_generated_version_markers() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        crate::generate_project(&crate::ProjectScaffold::new("App", "11.12.1", &root)).unwrap();
        // A version-shaped literal that is *not* a `ProjectBuilder::new`
        // argument must survive the upgrade untouched.
        let domain = root.join("src/domain/mod.rs");
        let source = std::fs::read_to_string(&domain)
            .unwrap()
            .replace("\"Main\"", "\"literal 11.12.1 must stay\"");
        std::fs::write(&domain, source).unwrap();

        let preview = upgrade_project(&root, "11.13.0", false).unwrap();
        assert!(!preview.applied);
        assert_eq!(preview.files.len(), 2);
        assert!(
            std::fs::read_to_string(root.join("src/lib.rs"))
                .unwrap()
                .contains("11.12.1")
        );

        let applied = upgrade_project(&root, "11.13.0", true).unwrap();
        assert!(applied.applied);
        assert!(
            std::fs::read_to_string(root.join("src/lib.rs"))
                .unwrap()
                .contains("11.13.0")
        );
        let domain = std::fs::read_to_string(domain).unwrap();
        assert!(domain.contains("ProjectBuilder::new(\"11.13.0\")"));
        assert!(domain.contains("literal 11.12.1 must stay"));
    }

    #[test]
    fn invalid_and_inconsistent_versions_fail_closed() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        crate::generate_project(&crate::ProjectScaffold::new("App", "11.12.1", &root)).unwrap();
        assert!(matches!(
            upgrade_project(&root, "next", false),
            Err(ScaffoldError::InvalidVersion(_))
        ));
        std::fs::write(
            root.join("mxrs.toml"),
            "[project]\nmendix_version = \"10.0.0\"\n",
        )
        .unwrap();
        assert!(matches!(
            upgrade_project(&root, "11.13.0", false),
            Err(ScaffoldError::VersionMismatch(_))
        ));
    }

    /// Both generators now declare `project = crate::build` next to the
    /// version. Upgrading must still find and rewrite the version without
    /// disturbing the composition root the attribute names, and must keep
    /// working for a project that names a deeper entry point by hand.
    #[test]
    fn application_attribute_keeps_its_project_entry_point_across_an_upgrade() {
        for entry_point in ["crate::build", "crate::application::build"] {
            let source = format!(
                "#[mxrs::application(version = \"11.12.1\", project = {entry_point})]\npub struct Application;\n"
            );
            assert_eq!(application_version(&source).as_deref(), Some("11.12.1"));
            assert_eq!(
                replace_application_version(&source, "11.12.1", "11.13.0").as_deref(),
                Some(
                    format!(
                        "#[mxrs::application(version = \"11.13.0\", project = {entry_point})]\npub struct Application;\n"
                    )
                    .as_str()
                )
            );
        }
    }

    /// The version-only attribute `mxrs new` emitted before the layering
    /// increment must keep upgrading, since it is still what every project
    /// already under version control declares.
    #[test]
    fn version_only_application_attribute_still_upgrades() {
        let source = "#[mxrs::application(version = \"11.12.1\")]\npub struct Application;\n";
        assert_eq!(application_version(source).as_deref(), Some("11.12.1"));
        assert_eq!(
            replace_application_version(source, "11.12.1", "11.13.0").as_deref(),
            Some("#[mxrs::application(version = \"11.13.0\")]\npub struct Application;\n")
        );
    }

    /// The layered layout and the pre-split one both exist in the wild, so an
    /// upgrade has to rewrite whichever flow modules a project actually has
    /// and leave the version literal alone everywhere else.
    #[test]
    fn upgrade_rewrites_layered_and_pre_split_flow_modules() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        let builder = "fn declarations() {\n    ::mxrs_dsl::ProjectBuilder::new(\"11.12.1\");\n}\n";
        for (relative, body) in [
            ("Cargo.toml", "[package]\nname = \"app\"\n"),
            (
                "src/lib.rs",
                concat!(
                    "#[mxrs::application(version = \"11.12.1\", ",
                    "project = crate::build)]\npub struct Application;\n"
                ),
            ),
            ("src/domain/mod.rs", "pub fn build() {}\n"),
            ("src/application/microflows/mod.rs", builder),
            ("src/presentation/nanoflows/mod.rs", builder),
            ("src/domain/flows/mod.rs", builder),
        ] {
            let path = root.join(relative);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, body).unwrap();
        }

        let report = upgrade_project(&root, "11.13.0", true).unwrap();
        assert_eq!(report.from, "11.12.1");
        // `src/domain/mod.rs` carries no version literal, so it is not an
        // update — the transaction reports only the four files it rewrote.
        assert_eq!(report.files.len(), 4);
        for relative in [
            "src/application/microflows/mod.rs",
            "src/presentation/nanoflows/mod.rs",
            "src/domain/flows/mod.rs",
        ] {
            let source = std::fs::read_to_string(root.join(relative)).unwrap();
            assert!(
                source.contains("ProjectBuilder::new(\"11.13.0\")"),
                "{relative} kept the old version"
            );
        }
        let library = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
        assert!(library.contains("version = \"11.13.0\""));
        assert!(library.contains("project = crate::build"));
    }

    /// `src/domain/documents/mod.rs` opens its `declarations()` with the same
    /// `ProjectBuilder::new("<version>")` call the flow modules use, so leaving
    /// it out of the upgrade would strand one generated file on the old version
    /// while its siblings moved — a difference nothing else in the project
    /// would surface.
    #[test]
    fn upgrade_rewrites_the_imported_documents_module_too() {
        let directory = tempfile::tempdir().unwrap();
        let root = directory.path().join("app");
        let documents = concat!(
            "//! Editable Cargo-native enumerations, constants, regular expressions, ",
            "scheduled events, and menus.\n\n",
            "fn declarations() -> ::mxrs_ir::ProjectDecl {\n",
            "    let mut project = ::mxrs_dsl::ProjectBuilder::new(\"11.12.1\");\n",
            "    project.module(\"Sales\", |module| {\n",
            "        module.constant(\"ReleaseNote\", |constant| {\n",
            // A version-shaped literal that is not a builder argument must
            // survive, the same way it does in `src/domain/mod.rs`.
            "            constant.value(\"pinned to 11.12.1\");\n",
            "        });\n",
            "    });\n",
            "    project.build()\n}\n",
        );
        for (relative, body) in [
            ("Cargo.toml", "[package]\nname = \"app\"\n"),
            (
                "src/lib.rs",
                concat!(
                    "#[mxrs::application(version = \"11.12.1\", ",
                    "project = crate::build)]\npub struct Application;\n"
                ),
            ),
            ("src/domain/mod.rs", "pub fn build() {}\n"),
            ("src/domain/documents/mod.rs", documents),
        ] {
            let path = root.join(relative);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, body).unwrap();
        }

        let report = upgrade_project(&root, "11.13.0", true).unwrap();
        assert_eq!(report.from, "11.12.1");
        assert!(
            report
                .files
                .iter()
                .any(|file| file.ends_with("src/domain/documents/mod.rs")),
            "the documents module was not reported as updated: {:?}",
            report.files
        );
        let updated = std::fs::read_to_string(root.join("src/domain/documents/mod.rs")).unwrap();
        assert!(updated.contains("ProjectBuilder::new(\"11.13.0\")"));
        assert!(!updated.contains("ProjectBuilder::new(\"11.12.1\")"));
        assert!(updated.contains("pinned to 11.12.1"));
    }

    #[test]
    fn compact_manifest_syntax_is_updated_instead_of_silently_skipped() {
        let source = "[project]\n  mendix_version=\"11.12.1\"\nname = \"App\"\n";
        assert_eq!(
            replace_manifest_version(source, "11.12.1", "11.13.0"),
            "[project]\n  mendix_version=\"11.13.0\"\nname = \"App\"\n"
        );
    }
}
