//! Phase 4 marker-type contract: the trait surface `mxrs-typegen`-generated
//! code implements, and the newtype `mxrs-dsl::EntityBuilder::association`
//! now *requires* in place of a raw string target. Kept here rather than in
//! `mxrs-typegen` itself so a user's generated-markers module only needs to
//! depend on `mxrs-ir` (already a transitive dependency via `mxrs-dsl`),
//! not on the codegen tool — the same "no capability exists only through
//! generated code" split `mxrs-macros` (Phase 8) is required to follow for
//! the same reason.
//!
//! **`mxrs-dsl` wiring** (`EntityBuilder::association`'s target parameter
//! is `Ref<M>`, not `impl Into<String>`): a typo'd or renamed association
//! target — even a same-module one — now fails `cargo build` via a
//! "no such marker type" error, not `mxrs-writer`'s runtime
//! `UnknownAssociationTarget`. The runtime check still exists and still
//! matters: a `Ref<M>` only proves the *marker type* exists (i.e. some
//! manifest once declared that name), not that the specific `ProjectDecl`
//! being written actually includes that entity — those are two different
//! guarantees, and only the second one is enforceable at compile time
//! without also making the whole `ProjectBuilder` invocation type-level
//! (out of scope for this pass). See
//! `mxrs-writer::domain::resolve_association`'s doc comment for the
//! consequence this has on local-vs-cross-module routing: a same-module
//! `Ref<M>` still resolves to a fully-qualified `"Module.Entity"` string
//! (there's no "short form" anymore), so routing can no longer key off
//! "does the target string contain a dot."
//!
//! `AssociationDecl.target` itself is still a plain `String`, deliberately:
//! only the *builder's* entry point requires a marker; the underlying IR
//! stays constructible directly (with a hand-written string target,
//! unqualified or qualified) for lower-level callers — `mxrs-writer`'s own
//! test suite does this to exercise `synchronize_domain_associations`
//! without going through `mxrs-dsl` at all.

use std::marker::PhantomData;

/// Implemented by a generated marker type for one Mendix entity (e.g.
/// `markers::Sales::Order`, generated from a manifest's `Sales.Order`
/// declaration). Zero-sized — it exists purely to be a distinct type the
/// compiler can check, not to hold data.
///
/// The `#[diagnostic::on_unimplemented]` below is Phase 8's M8.4 (per the
/// phased roadmap): a `project! {}` association whose target doesn't
/// resolve to a real marker type fails via this trait bound
/// (`Ref::<BadTarget>::new()` inside the macro's own expansion) — without
/// this attribute the compiler's default message is the generic "the trait
/// bound `BadTarget: EntityMarker` is not satisfied", which says nothing
/// about *why* that matters here. This doesn't change *where* the error
/// points (rustc already spans the type argument accurately — the
/// attribute only rewrites the *message*), but that's the same "spirit of
/// M8.4" this crate's own custom `syn::Error`s already deliver at
/// macro-parse time: turn a generic error into one that names the actual
/// mxrs concept a caller got wrong.
#[cfg_attr(
    not(doctest),
    diagnostic::on_unimplemented(
        message = "`{Self}` is not a Mendix entity marker",
        label = "expected a type implementing `EntityMarker`, generated by mxrs-typegen or hand-implemented",
        note = "if this came from `project! {{ ... -> {Self} as ... }}`, check the schema manifest declares this entity, or that the path is spelled/qualified correctly"
    )
)]
pub trait EntityMarker: 'static {
    /// The owning module's name, exactly as declared in the manifest.
    const MODULE: &'static str;
    /// The entity's own name, exactly as declared in the manifest.
    const NAME: &'static str;

    fn qualified_name() -> String {
        format!("{}.{}", Self::MODULE, Self::NAME)
    }
}

/// Built-in Mendix system entities that application entities may specialize.
/// Keeping these as ordinary marker types gives `generalizes` the same
/// compile-time guarantee as an application-owned parent without asking a
/// generated project to redeclare the System module.
#[allow(non_snake_case)]
pub mod system {
    use super::EntityMarker;

    macro_rules! system_entity {
        ($name:ident) => {
            pub struct $name;
            impl EntityMarker for $name {
                const MODULE: &'static str = "System";
                const NAME: &'static str = stringify!($name);
            }
        };
    }

    system_entity!(User);
    system_entity!(FileDocument);
    system_entity!(Image);
}

/// Implemented by a Cargo-native Mendix enumeration. Attribute derives use
/// this marker to resolve the qualified name without embedding a string.
pub trait EnumerationMarker: 'static {
    const MODULE: &'static str;
    const NAME: &'static str;

    fn qualified_name() -> String {
        format!("{}.{}", Self::MODULE, Self::NAME)
    }
}

/// A Cargo-native single-reference field. It carries no runtime value; the
/// entity derive lowers its target and cardinality into the domain model.
#[derive(Debug, Clone, Copy, Default)]
pub struct Reference<T: EntityMarker>(PhantomData<T>);

/// A Cargo-native reference-set field. Like [`Reference`], this is schema
/// information consumed by `#[derive(MxEntity)]`.
#[derive(Debug, Clone, Copy, Default)]
pub struct ReferenceSet<T: EntityMarker>(PhantomData<T>);

/// Implemented by a generated marker type for one attribute of one entity
/// (e.g. `markers::Sales::Order_Number`, generated from a manifest entity's
/// `attributes` list).
#[cfg_attr(
    not(doctest),
    diagnostic::on_unimplemented(
        message = "`{Self}` is not a Mendix attribute marker",
        label = "expected a type implementing `AttributeMarker`, generated by mxrs-typegen or hand-implemented"
    )
)]
pub trait AttributeMarker: 'static {
    type Entity: EntityMarker;
    const NAME: &'static str;
}

/// Implemented by a generated marker type for one *declared* association of
/// one entity (e.g. `markers::Sales::Order_Order_Customer`, generated from
/// a manifest entity's `associations` list — see `mxrs-typegen`'s manifest
/// docs, or auto-generated inline by `project! {}` from an `association`
/// statement — see `mxrs-macros::expand::expand_entity_markers`).
/// `EntityBuilder::association<A: AssociationMarker>()` requires this
/// directly (no raw `name`/`target`/`association_type` parameters at all
/// anymore) — validates the whole declaration against the manifest/macro
/// input, not just the target. `A::From` is *not* cross-checked against the
/// entity `association` is actually called on: `EntityBuilder` has no
/// compile-time or runtime handle on its own qualified name at that point,
/// so this stays a one-sided guarantee, same boundary `Ref<M>` already
/// draws for the target-only case (see `EntityBuilder::association`'s own
/// doc comment for the full reasoning).
#[cfg_attr(
    not(doctest),
    diagnostic::on_unimplemented(
        message = "`{Self}` is not a Mendix association marker",
        label = "expected a type implementing `AssociationMarker`, generated by mxrs-typegen or hand-implemented"
    )
)]
pub trait AssociationMarker: 'static {
    /// The entity this association is declared on (the one carrying the
    /// foreign key — same "FROM" convention as
    /// `mxrs_model::association::Association::from_entity_id`).
    type From: EntityMarker;
    /// The entity this association points to.
    type To: EntityMarker;
    const NAME: &'static str;
    const ASSOCIATION_TYPE: crate::AssociationType;
}

/// Implemented by a generated marker type for one microflow (e.g.
/// `markers::Sales::ACT_Notify`, generated from a manifest module's
/// `microflows` list). Unlike `EntityMarker`, this is module-scoped, not
/// entity-scoped — a microflow doesn't belong to an entity. Only a name and
/// owning module are captured, not the microflow's own body: this trait
/// exists purely so `FlowBuilder::call_microflow`'s target can be
/// marker-checked the same way `EntityBuilder::association`'s target is
/// (closes the last remaining un-marker-checked reference kind from Phase 4's
/// original gap list), not to make microflow bodies themselves manifest-driven.
#[cfg_attr(
    not(doctest),
    diagnostic::on_unimplemented(
        message = "`{Self}` is not a Mendix microflow marker",
        label = "expected a type implementing `MicroflowMarker`, generated by mxrs-typegen or hand-implemented",
        note = "if this came from `project! {{ call {Self} ... }}`, check the schema manifest declares this microflow, or that the path is spelled/qualified correctly"
    )
)]
pub trait MicroflowMarker: 'static {
    /// The owning module's name, exactly as declared in the manifest.
    const MODULE: &'static str;
    /// The microflow's own name, exactly as declared in the manifest.
    const NAME: &'static str;

    fn qualified_name() -> String {
        format!("{}.{}", Self::MODULE, Self::NAME)
    }
}

/// A typed reference to a microflow, mirroring `Ref<M: EntityMarker>` but for
/// `FlowBuilder::call_microflow`'s target — see `MicroflowMarker`'s doc
/// comment for why this is a separate type rather than reusing `Ref`
/// (different marker trait, no `EntityMarker` bound to satisfy).
#[derive(Debug)]
pub struct MicroflowRef<M: MicroflowMarker>(PhantomData<M>);

impl<M: MicroflowMarker> MicroflowRef<M> {
    pub fn new() -> Self {
        MicroflowRef(PhantomData)
    }

    pub fn qualified_name(&self) -> String {
        M::qualified_name()
    }
}

impl<M: MicroflowMarker> Default for MicroflowRef<M> {
    fn default() -> Self {
        Self::new()
    }
}

impl<M: MicroflowMarker> Clone for MicroflowRef<M> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<M: MicroflowMarker> Copy for MicroflowRef<M> {}

/// Implemented by a generated marker type for one nanoflow (mirrors
/// [`MicroflowMarker`] exactly — same module-scoped, name-only contract).
/// `mxrs-typegen` generates these from a manifest even though nanoflows do
/// not yet have a Cargo-native authoring builder. This lets pages reference
/// imported nanoflows with compile-time checked names while their bodies
/// remain losslessly backed by the imported snapshot. Exists so a page widget that calls or
/// sources data from an existing nanoflow (e.g.
/// `WidgetDecl::DataView`'s nanoflow data source, or a button's
/// nanoflow-calling action) can be marker-checked instead of taking a raw
/// `impl Into<String>`, the same guarantee `MicroflowRef<M>` already gives
/// microflow-calling activities.
#[cfg_attr(
    not(doctest),
    diagnostic::on_unimplemented(
        message = "`{Self}` is not a Mendix nanoflow marker",
        label = "expected a type implementing `NanoflowMarker`, generated by mxrs-typegen or hand-implemented",
        note = "this marker names an existing nanoflow so it can be referenced with compile-time checking"
    )
)]
pub trait NanoflowMarker: 'static {
    /// The owning module's name, exactly as declared in the manifest.
    const MODULE: &'static str;
    /// The nanoflow's own name, exactly as declared in the manifest.
    const NAME: &'static str;

    fn qualified_name() -> String {
        format!("{}.{}", Self::MODULE, Self::NAME)
    }
}

/// A typed reference to a nanoflow, mirroring [`MicroflowRef`] — see
/// [`NanoflowMarker`]'s doc comment for why this is a separate type.
#[derive(Debug)]
pub struct NanoflowRef<N: NanoflowMarker>(PhantomData<N>);

impl<N: NanoflowMarker> NanoflowRef<N> {
    pub fn new() -> Self {
        NanoflowRef(PhantomData)
    }

    pub fn qualified_name(&self) -> String {
        N::qualified_name()
    }
}

impl<N: NanoflowMarker> Default for NanoflowRef<N> {
    fn default() -> Self {
        Self::new()
    }
}

impl<N: NanoflowMarker> Clone for NanoflowRef<N> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<N: NanoflowMarker> Copy for NanoflowRef<N> {}

/// A typed reference to an entity, carrying no runtime state beyond what's
/// needed to resolve back to the qualified name `mxrs-writer` already
/// expects (`"Module.Entity"`) — so once `mxrs-dsl` is wired to accept
/// `Ref<M>` in place of a raw target string, existing target-resolution
/// code in `mxrs-writer::domain` (which already branches on a `.` in the
/// string) needs no changes at all.
#[derive(Debug)]
pub struct Ref<M: EntityMarker>(PhantomData<M>);

impl<M: EntityMarker> Ref<M> {
    pub fn new() -> Self {
        Ref(PhantomData)
    }

    pub fn qualified_name(&self) -> String {
        M::qualified_name()
    }
}

impl<M: EntityMarker> Default for Ref<M> {
    fn default() -> Self {
        Self::new()
    }
}

impl<M: EntityMarker> Clone for Ref<M> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<M: EntityMarker> Copy for Ref<M> {}

/// A value-level handle to one attribute of one entity.
///
/// `#[mxrs::entity]` gives every field an accessor returning one of these
/// (`Order::number()`), so authored code names an attribute through the
/// entity it belongs to instead of through a separately generated marker
/// type. The handle is zero-sized: everything it knows lives in `A`.
#[derive(Debug)]
pub struct AttributeRef<A: AttributeMarker>(PhantomData<A>);

impl<A: AttributeMarker> AttributeRef<A> {
    pub const fn new() -> Self {
        AttributeRef(PhantomData)
    }

    /// The attribute's Mendix name, exactly as the model stores it.
    pub fn name(&self) -> &'static str {
        A::NAME
    }

    /// `Module.Entity.Attribute`.
    pub fn qualified_name(&self) -> String {
        format!("{}.{}", A::Entity::qualified_name(), A::NAME)
    }
}

impl<A: AttributeMarker> Default for AttributeRef<A> {
    fn default() -> Self {
        Self::new()
    }
}

impl<A: AttributeMarker> Clone for AttributeRef<A> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<A: AttributeMarker> Copy for AttributeRef<A> {}

/// A value-level handle to one association, the counterpart of
/// [`AttributeRef`] for `Reference<T>`/`ReferenceSet<T>` fields.
#[derive(Debug)]
pub struct AssociationRef<A: AssociationMarker>(PhantomData<A>);

impl<A: AssociationMarker> AssociationRef<A> {
    pub const fn new() -> Self {
        AssociationRef(PhantomData)
    }

    /// The association's Mendix name, exactly as the model stores it.
    pub fn name(&self) -> &'static str {
        A::NAME
    }

    /// `Module.Association` — the form the native model stores.
    pub fn qualified_name(&self) -> String {
        format!("{}.{}", A::From::MODULE, A::NAME)
    }
}

impl<A: AssociationMarker> Default for AssociationRef<A> {
    fn default() -> Self {
        Self::new()
    }
}

impl<A: AssociationMarker> Clone for AssociationRef<A> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<A: AssociationMarker> Copy for AssociationRef<A> {}

#[cfg(test)]
mod tests {
    use super::*;

    struct Order;
    impl EntityMarker for Order {
        const MODULE: &'static str = "Sales";
        const NAME: &'static str = "Order";
    }

    struct OrderNumber;
    impl AttributeMarker for OrderNumber {
        type Entity = Order;
        const NAME: &'static str = "Number";
    }

    struct Customer;
    impl EntityMarker for Customer {
        const MODULE: &'static str = "Sales";
        const NAME: &'static str = "Customer";
    }

    struct OrderCustomer;
    impl AssociationMarker for OrderCustomer {
        type From = Order;
        type To = Customer;
        const NAME: &'static str = "Order_Customer";
        const ASSOCIATION_TYPE: crate::AssociationType = crate::AssociationType::Reference;
    }

    #[test]
    fn qualified_name_joins_module_and_entity() {
        assert_eq!(Order::qualified_name(), "Sales.Order");
    }

    #[test]
    fn ref_resolves_to_its_marker_qualified_name() {
        let r: Ref<Order> = Ref::new();
        assert_eq!(r.qualified_name(), "Sales.Order");
    }

    #[test]
    fn attribute_marker_names_its_owning_entity() {
        assert_eq!(OrderNumber::NAME, "Number");
        assert_eq!(
            <OrderNumber as AttributeMarker>::Entity::qualified_name(),
            "Sales.Order"
        );
    }

    struct ActNotify;
    impl MicroflowMarker for ActNotify {
        const MODULE: &'static str = "Sales";
        const NAME: &'static str = "ACT_Notify";
    }

    #[test]
    fn microflow_marker_qualified_name_joins_module_and_name() {
        assert_eq!(ActNotify::qualified_name(), "Sales.ACT_Notify");
    }

    #[test]
    fn microflow_ref_resolves_to_its_marker_qualified_name() {
        let r: MicroflowRef<ActNotify> = MicroflowRef::new();
        assert_eq!(r.qualified_name(), "Sales.ACT_Notify");
    }

    struct ActFetchOrder;
    impl NanoflowMarker for ActFetchOrder {
        const MODULE: &'static str = "Sales";
        const NAME: &'static str = "NF_FetchOrder";
    }

    #[test]
    fn nanoflow_marker_qualified_name_joins_module_and_name() {
        assert_eq!(ActFetchOrder::qualified_name(), "Sales.NF_FetchOrder");
    }

    #[test]
    fn nanoflow_ref_resolves_to_its_marker_qualified_name() {
        let r: NanoflowRef<ActFetchOrder> = NanoflowRef::new();
        assert_eq!(r.qualified_name(), "Sales.NF_FetchOrder");
    }

    #[test]
    fn association_marker_names_its_from_to_and_type() {
        assert_eq!(OrderCustomer::NAME, "Order_Customer");
        assert_eq!(
            <OrderCustomer as AssociationMarker>::From::qualified_name(),
            "Sales.Order"
        );
        assert_eq!(
            <OrderCustomer as AssociationMarker>::To::qualified_name(),
            "Sales.Customer"
        );
        assert_eq!(
            OrderCustomer::ASSOCIATION_TYPE,
            crate::AssociationType::Reference
        );
    }
}
