//! Detects pages built entirely from the widget vocabulary
//! `mxrs-dsl`/`mxrs-writer` can author (see `mxrs_ir::page`'s doc comment)
//! and renders them as reviewable `mxrs-dsl` source text.
//!
//! **Deliberately not wired into the live `build()`/`.mpr` output** (unlike
//! domain entities, which `render`/`import_cargo_project` do wire into
//! `src/domain/mod.rs`'s `project! {}` call). Two concrete risks made that
//! the wrong default for this pass:
//!
//! 1. **Silent fidelity loss on the very first rebuild.** This IR captures
//!    far less than a real Studio-Pro-authored page can carry (no
//!    conditional visibility, no dynamic classes, no data binding, no
//!    pluggable widgets — see `mxrs_ir::page`). If a detected page were
//!    auto-wired into `ProjectDecl.modules[].pages`, the very first
//!    `cargo mxrs build` after import would silently re-derive that page
//!    from the narrower IR and drop anything outside it — worse than
//!    leaving it opaque.
//! 2. **`layout` isn't reliably recoverable from the decoded snapshot.**
//!    `mxrs_model::page::Page::layout_id` reads a page's `Layout`/`LayoutId`
//!    field (mxrb's older, hand-rolled-writer page shape); it does not
//!    (yet) decode the modern schema-driven `LayoutCall.Layout` by-name
//!    reference `mxrs-writer::page_compiler` itself writes and
//!    `mxrs-model::page::extract_layout` was never extended to read back
//!    (a real, separately-trackable gap in `mxrs-model`, out of scope
//!    here). Concretely: a real imported page's `layout` is usually
//!    unresolvable, so the rendered source always leaves a `TODO` for it.
//!
//! Given both, this module writes `src/domain/pages.rs` as syntactically
//! valid but **uncompiled** reference source (not declared as a module from
//! `src/domain/mod.rs` or anywhere else in the generated crate — an `.rs`
//! file cargo never sees is simply inert). Adopting a page means copying
//! the generated function's body into a `module.page(...)` call the
//! developer actually wires up themselves, after filling in the `layout`
//! TODO and reviewing what (if anything) was dropped.
//!
//! **Widget vocabulary detected**: `container`/`text`/`button` only — not
//! `layout_grid`. `mxrs-model::page::layout_grid_widget`'s own decode is a
//! lossy widget-*count* summary (see that function's `"widget_count"`
//! field), not the actual nested widgets, so a `LayoutGrid` can never be
//! losslessly reconstructed from the decoded view this module consumes;
//! extending that decoder to be lossless is a separate, `mxrs-model`-side
//! follow-up. `mxrs-writer::page_compiler` still supports writing
//! `LayoutGrid` for pages hand-authored from scratch — only *import
//! detection* is narrower.

use std::fmt::Write as _;

use mxrs_bson::Document;
use mxrs_ir::page::{ButtonAction, PageDecl, WidgetDecl};
use mxrs_model::Module;
use mxrs_model::page::{Page, Widget};

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct PageExportReport {
    /// Pages built entirely from the detected widget vocabulary — rendered
    /// into `src/domain/pages.rs` for review.
    pub typed_candidates: usize,
    /// Every other page (pluggable widgets, data binding, conditional
    /// visibility, security roles, ...) — stays exactly as opaque as
    /// before this pass, served from the generated snapshot.
    pub opaque: usize,
}

/// Renders every convertible page across every module into one reviewable
/// source file, alongside a count of what wasn't convertible. Returns
/// `None` when there is nothing to show (no point writing an empty file).
pub fn render_pages_review(modules: &[Module]) -> (Option<String>, PageExportReport) {
    let mut report = PageExportReport::default();
    let mut functions = Vec::new();
    for module in modules {
        let module_name = module.name.as_deref().unwrap_or("Unnamed");
        for page in &module.pages {
            match try_convert_page(page) {
                Some(decl) => {
                    report.typed_candidates += 1;
                    functions.push(render_page_function(module_name, &decl));
                }
                None => report.opaque += 1,
            }
        }
    }
    if functions.is_empty() {
        return (None, report);
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by `mxrs-exporter` for review only — this file is NOT"
    );
    let _ = writeln!(
        out,
        "// declared as a module anywhere and is never compiled. Each function"
    );
    let _ = writeln!(
        out,
        "// below reproduces one page detected as buildable from mxrs-dsl's"
    );
    let _ = writeln!(
        out,
        "// native/structural widget vocabulary (see mxrs_ir::page's doc"
    );
    let _ = writeln!(
        out,
        "// comment). To adopt one: copy its body into your own module setup,"
    );
    let _ = writeln!(
        out,
        "// e.g. `module.page(\"Name\", |p| {{ .. body .. }});`, filling in the"
    );
    let _ = writeln!(
        out,
        "// `layout` TODO (not recoverable from the imported snapshot — see"
    );
    let _ = writeln!(out, "// this crate's `page_export` module doc for why).");
    out.push('\n');
    for function in functions {
        out.push_str(&function);
        out.push('\n');
    }
    (Some(out), report)
}

fn try_convert_page(page: &Page) -> Option<PageDecl> {
    let name = page.name.clone()?;
    if page.data_source.is_some() {
        return None;
    }
    if !page.allowed_module_roles.is_empty() {
        return None;
    }
    if !page.appearance_class.is_empty() || !page.appearance_style.is_empty() {
        return None;
    }
    let widgets = page
        .widgets
        .iter()
        .map(try_convert_widget)
        .collect::<Option<Vec<_>>>()?;

    let mut decl = PageDecl::new(name);
    decl.documentation = page.documentation.clone();
    decl.url = page.url.clone();
    if !page.title.is_empty() {
        decl.title = Some(page.title.clone());
    }
    decl.widgets = widgets;
    Some(decl)
}

fn try_convert_widget(widget: &Widget) -> Option<WidgetDecl> {
    match widget.widget_type.as_str() {
        "container" => {
            if !widget.events.is_empty() || !only_keys(&widget.options, &["class", "style"]) {
                return None;
            }
            let children = widget
                .children
                .iter()
                .map(try_convert_widget)
                .collect::<Option<Vec<_>>>()?;
            Some(WidgetDecl::Container {
                name: widget.name.clone(),
                class: string_option(&widget.options, "class"),
                style: string_option(&widget.options, "style"),
                children,
            })
        }
        "text" => {
            if !widget.events.is_empty()
                || !only_keys(&widget.options, &["class", "style", "caption"])
            {
                return None;
            }
            let caption = string_option(&widget.options, "caption")?;
            Some(WidgetDecl::Text {
                name: widget.name.clone(),
                caption,
                class: string_option(&widget.options, "class"),
            })
        }
        "button" => {
            if !only_keys(&widget.options, &["class", "style", "caption"]) {
                return None;
            }
            let action = match widget.events.as_slice() {
                [] => ButtonAction::None,
                [event]
                    if event.get_str("kind").ok() == Some("action")
                        && event.get_str("handler").ok() == Some("close_page")
                        && event.get_str("event").ok() == Some("on_click") =>
                {
                    ButtonAction::ClosePage
                }
                _ => return None,
            };
            Some(WidgetDecl::Button {
                name: widget.name.clone(),
                caption: string_option(&widget.options, "caption").unwrap_or_default(),
                class: string_option(&widget.options, "class"),
                action,
            })
        }
        _ => None,
    }
}

fn only_keys(document: &Document, allowed: &[&str]) -> bool {
    document.keys().all(|key| allowed.contains(&key.as_str()))
}

fn string_option(document: &Document, key: &str) -> Option<String> {
    document.get_str(key).ok().map(str::to_string)
}

fn render_page_function(module_name: &str, decl: &PageDecl) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/// `{module_name}.{}`", decl.name);
    let _ = writeln!(
        out,
        "pub fn {}(module: &mut ::mxrs_dsl::ModuleBuilder) {{",
        to_snake_case(&decl.name)
    );
    let _ = writeln!(out, "    module.page({:?}, |p| {{", decl.name);
    if !decl.documentation.is_empty() {
        let _ = writeln!(out, "        p.documentation({:?});", decl.documentation);
    }
    if !decl.url.is_empty() {
        let _ = writeln!(out, "        p.url({:?});", decl.url);
    }
    if let Some(title) = &decl.title {
        let _ = writeln!(out, "        p.title({title:?});");
    }
    match &decl.layout {
        Some(layout) => {
            let _ = writeln!(
                out,
                "        p.layout({:?}, {:?});",
                layout.qualified_name, layout.parameter
            );
        }
        None if !decl.widgets.is_empty() => {
            let _ = writeln!(
                out,
                "        // TODO: layout not recoverable from the imported snapshot; set it, e.g.:"
            );
            let _ = writeln!(
                out,
                "        // p.layout(\"YourModule.YourLayout\", \"Main\");"
            );
        }
        None => {}
    }
    for widget in &decl.widgets {
        out.push_str(&render_widget(widget, 2));
    }
    let _ = writeln!(out, "    }});");
    let _ = writeln!(out, "}}");
    out
}

fn render_widget(widget: &WidgetDecl, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let mut out = String::new();
    match widget {
        WidgetDecl::Container {
            name,
            class,
            style,
            children,
        } => {
            let _ = writeln!(out, "{pad}w.container(|w| {{");
            if let Some(name) = name {
                let _ = writeln!(out, "{pad}    w.name({name:?});");
            }
            if let Some(class) = class {
                let _ = writeln!(out, "{pad}    w.class({class:?});");
            }
            if let Some(style) = style {
                let _ = writeln!(out, "{pad}    w.style({style:?});");
            }
            for child in children {
                out.push_str(&render_widget(child, indent + 1));
            }
            let _ = writeln!(out, "{pad}}});");
        }
        WidgetDecl::LayoutGrid { .. } => {
            // Unreachable from `try_convert_widget` (see this module's doc
            // comment) — kept exhaustive rather than `unreachable!()` so a
            // future widening of import detection doesn't silently need to
            // remember to add this arm.
            let _ = writeln!(
                out,
                "{pad}// TODO: layout_grid import detection isn't supported yet"
            );
        }
        WidgetDecl::Text { caption, .. } => {
            let _ = writeln!(out, "{pad}w.text({caption:?});");
        }
        WidgetDecl::Button {
            caption, action, ..
        } => {
            let _ = writeln!(out, "{pad}w.button({caption:?}, |b| {{");
            if *action == ButtonAction::ClosePage {
                let _ = writeln!(out, "{pad}    b.close_page();");
            }
            let _ = writeln!(out, "{pad}}});");
        }
    }
    out
}

/// `OrderOverview` -> `order_overview`. A defensive, not exhaustive, name
/// sanitizer mirroring `mxrs-exporter`'s own `sanitize_ident` for the
/// domain-model renderer: non-alphanumeric characters become `_`.
fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if index != 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else if ch.is_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn container(children: Vec<Widget>) -> Widget {
        Widget {
            widget_type: "container".into(),
            name: Some("row".into()),
            options: mxrs_bson::doc! { "class": "row" },
            events: vec![],
            children,
        }
    }

    fn text(caption: &str) -> Widget {
        Widget {
            widget_type: "text".into(),
            name: Some("hint".into()),
            options: mxrs_bson::doc! { "caption": caption },
            events: vec![],
            children: vec![],
        }
    }

    fn close_button(caption: &str) -> Widget {
        Widget {
            widget_type: "button".into(),
            name: Some("close".into()),
            options: mxrs_bson::doc! { "caption": caption },
            events: vec![
                mxrs_bson::doc! { "kind": "action", "handler": "close_page", "event": "on_click" },
            ],
            children: vec![],
        }
    }

    fn bare_page(name: &str, widgets: Vec<Widget>) -> Page {
        Page::from_bson(&mxrs_bson::doc! {
            "$ID": uuid::Uuid::new_v4().to_string(),
            "$Type": "Forms$Page",
            "Name": name,
            "Widgets": mxrs_bson::build_array(
                widgets.into_iter().map(widget_to_bson).collect(),
                3,
            ),
        })
    }

    fn widget_to_bson(widget: Widget) -> mxrs_bson::Bson {
        match widget.widget_type.as_str() {
            "container" => mxrs_bson::Bson::Document(mxrs_bson::doc! {
                "$ID": uuid::Uuid::new_v4().to_string(),
                "$Type": "Forms$DivContainer",
                "Name": widget.name.unwrap_or_default(),
                "Class": widget.options.get_str("class").unwrap_or("").to_string(),
                "Widgets": mxrs_bson::build_array(
                    widget.children.into_iter().map(widget_to_bson).collect(),
                    3,
                ),
            }),
            "text" => {
                let mut doc = mxrs_bson::doc! {
                    "$ID": uuid::Uuid::new_v4().to_string(),
                    "$Type": "Forms$DynamicText",
                    "Name": widget.name.unwrap_or_default(),
                    "Content": widget.options.get_str("caption").unwrap_or("").to_string(),
                };
                if let Ok(expression) = widget.options.get_str("visible") {
                    doc.insert(
                        "ConditionalVisibilitySettings",
                        mxrs_bson::doc! {
                            "$ID": uuid::Uuid::new_v4().to_string(),
                            "$Type": "Forms$ConditionalVisibilitySettings",
                            "Expression": expression.to_string(),
                        },
                    );
                }
                mxrs_bson::Bson::Document(doc)
            }
            "button" => mxrs_bson::Bson::Document(mxrs_bson::doc! {
                "$ID": uuid::Uuid::new_v4().to_string(),
                "$Type": "Forms$ActionButton",
                "Name": widget.name.unwrap_or_default(),
                "Caption": widget.options.get_str("caption").unwrap_or("").to_string(),
                "Action": { "$Type": "Forms$ClosePageClientAction" },
            }),
            other => panic!("unsupported test widget type {other}"),
        }
    }

    #[test]
    fn a_page_built_from_container_text_and_close_button_converts() {
        let page = bare_page(
            "OrderOverview",
            vec![container(vec![
                text("Manage your orders"),
                close_button("Close"),
            ])],
        );
        let decl = try_convert_page(&page).expect("should convert");
        assert_eq!(decl.name, "OrderOverview");
        assert_eq!(decl.widgets.len(), 1);
    }

    #[test]
    fn render_pages_review_counts_typed_and_opaque_pages_separately() {
        let convertible = bare_page("Simple", vec![text("hi")]);
        let unsupported = bare_page(
            "WithVisibility",
            vec![Widget {
                widget_type: "text".into(),
                name: Some("hint".into()),
                options: mxrs_bson::doc! { "caption": "hi", "visible": "$currentObject/Active" },
                events: vec![],
                children: vec![],
            }],
        );
        let module = Module {
            id: "m".into(),
            name: Some("Sales".into()),
            sort_index: None,
            from_app_store: false,
            app_store_guid: None,
            app_store_version: None,
            export_level: "Hidden".into(),
            domain_model: None,
            pages: vec![convertible, unsupported],
            microflows: vec![],
            nanoflows: vec![],
            rules: vec![],
            menus: vec![],
            module_roles: vec![],
            artifact_units: vec![],
        };

        let (source, report) = render_pages_review(std::slice::from_ref(&module));
        assert_eq!(report.typed_candidates, 1);
        assert_eq!(report.opaque, 1);
        let source = source.expect("one convertible page should still produce a file");
        assert!(source.contains("pub fn simple"));
        assert!(!source.contains("with_visibility"));
    }

    #[test]
    fn a_page_with_a_data_bound_text_widget_is_left_opaque() {
        let page = bare_page(
            "Bound",
            vec![Widget {
                widget_type: "text".into(),
                name: Some("hint".into()),
                options: mxrs_bson::doc! { "attribute": "Order/Number" },
                events: vec![],
                children: vec![],
            }],
        );
        assert!(try_convert_page(&page).is_none());
    }
}
