use mxrs_ir::declaration::{
    AssociationDecl, AssociationOwner, AssociationStorage, AssociationType, AttributeDecl,
    AttributeType, EntityDecl,
};
use mxrs_ir::{EntityMarker, Ref};

pub struct EntityBuilder {
    decl: EntityDecl,
}

impl EntityBuilder {
    pub(crate) fn new(name: impl Into<String>) -> Self {
        EntityBuilder {
            decl: EntityDecl::new(name),
        }
    }

    pub(crate) fn into_decl(self) -> EntityDecl {
        self.decl
    }

    pub fn documentation(&mut self, text: impl Into<String>) -> &mut Self {
        self.decl.documentation = text.into();
        self
    }

    pub fn persistable(&mut self, value: bool) -> &mut Self {
        self.decl.persistable = value;
        self
    }

    pub fn string(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::String)
    }

    pub fn integer(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Integer)
    }

    pub fn long(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Long)
    }

    pub fn float(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Float)
    }

    pub fn decimal(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Decimal)
    }

    pub fn boolean(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Boolean)
    }

    pub fn datetime(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::DateTime)
    }

    pub fn autonumber(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::AutoNumber)
    }

    pub fn hash_string(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::HashString)
    }

    pub fn binary(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Binary)
    }

    pub fn enumeration(
        &mut self,
        name: impl Into<String>,
        enumeration: impl Into<String>,
    ) -> &mut AttributeDecl {
        let attribute = self.push_attribute(name, AttributeType::Enumeration);
        attribute.enumeration = Some(enumeration.into());
        attribute
    }

    /// Declares an association from this entity to `target` — a
    /// compile-time marker type (`mxrs_ir::Ref<M>`, generated by
    /// `mxrs-typegen` from a schema manifest, or hand-implemented; see
    /// `mxrs_ir::markers`), not a raw string. A typo'd or renamed target
    /// fails `cargo build` instead of `mxrs-writer`'s runtime
    /// `UnknownAssociationTarget`/`UnknownCrossModuleAssociationTarget`
    /// (which still runs too — see `mxrs_ir::markers`' doc comment for why
    /// both checks matter). Works identically for a same-module or
    /// cross-module target: `Ref<M>::qualified_name()` always resolves to
    /// `"Module.Entity"`, and `mxrs-writer` routes on the resolved module,
    /// not on whether the string happens to contain a dot.
    ///
    /// Defaults to `AssociationOwner::Default`/`AssociationStorage::Column`; set the
    /// returned `AssociationDecl`'s public fields directly to override.
    pub fn association<M: EntityMarker>(
        &mut self,
        name: impl Into<String>,
        target: Ref<M>,
        association_type: AssociationType,
    ) -> &mut AssociationDecl {
        self.decl.associations.push(AssociationDecl {
            name: name.into(),
            target: target.qualified_name(),
            association_type,
            owner: AssociationOwner::Default,
            storage: AssociationStorage::Column,
            documentation: String::new(),
        });
        self.decl.associations.last_mut().expect("just pushed")
    }

    fn push_attribute(
        &mut self,
        name: impl Into<String>,
        attribute_type: AttributeType,
    ) -> &mut AttributeDecl {
        self.decl
            .attributes
            .push(AttributeDecl::new(name, attribute_type));
        self.decl.attributes.last_mut().expect("just pushed")
    }
}
