use mxrs_ir::declaration::{
    AssociationDecl, AssociationOwner, AssociationStorage, AttributeDecl, AttributeType, EntityDecl,
};
use mxrs_ir::{AssociationMarker, EntityMarker};

pub struct EntityBuilder {
    decl: EntityDecl,
}

impl EntityBuilder {
    pub(crate) fn new(name: impl Into<String>) -> Self {
        EntityBuilder {
            decl: EntityDecl::new(name),
        }
    }

    pub(crate) fn into_decl(self) -> EntityDecl {
        self.decl
    }

    pub fn documentation(&mut self, text: impl Into<String>) -> &mut Self {
        self.decl.documentation = text.into();
        self
    }

    pub fn persistable(&mut self, value: bool) -> &mut Self {
        self.decl.persistable = value;
        self
    }

    pub fn string(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::String)
    }

    pub fn integer(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Integer)
    }

    pub fn long(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Long)
    }

    pub fn float(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Float)
    }

    pub fn decimal(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Decimal)
    }

    pub fn boolean(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Boolean)
    }

    pub fn datetime(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::DateTime)
    }

    pub fn autonumber(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::AutoNumber)
    }

    pub fn hash_string(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::HashString)
    }

    pub fn binary(&mut self, name: impl Into<String>) -> &mut AttributeDecl {
        self.push_attribute(name, AttributeType::Binary)
    }

    pub fn enumeration(
        &mut self,
        name: impl Into<String>,
        enumeration: impl Into<String>,
    ) -> &mut AttributeDecl {
        let attribute = self.push_attribute(name, AttributeType::Enumeration);
        attribute.enumeration = Some(enumeration.into());
        attribute
    }

    /// Declares an association from this entity, identified entirely by
    /// `A` — a compile-time marker type implementing
    /// `mxrs_ir::AssociationMarker` (generated by `mxrs-typegen` from a
    /// schema manifest, or auto-generated by `project! {}` from an inline
    /// `association` statement; see `mxrs_ir::markers`). Name, target, and
    /// association type are all read off `A`'s associated consts/types —
    /// there is no raw-string or raw-`AssociationType` parameter to get out
    /// of sync with the manifest, closing the gap `AssociationMarker`'s own
    /// doc comment used to describe as deliberately left open. A typo'd or
    /// renamed target still fails `cargo build` (via `A::To: EntityMarker`)
    /// instead of `mxrs-writer`'s runtime
    /// `UnknownAssociationTarget`/`UnknownCrossModuleAssociationTarget`
    /// (which still runs too — see `mxrs_ir::markers`' doc comment for why
    /// both checks matter). Works identically for a same-module or
    /// cross-module target: `A::To::qualified_name()` always resolves to
    /// `"Module.Entity"`, and `mxrs-writer` routes on the resolved module,
    /// not on whether the string happens to contain a dot.
    ///
    /// Deliberately not checked here (same reasoning `Ref<M>` already
    /// documents for the target-only case): that `A::From` actually names
    /// *this* entity. `EntityBuilder` has no compile-time or runtime handle
    /// on its own qualified name at this point in construction — enforcing
    /// that would mean making the whole `ProjectBuilder` invocation
    /// type-level, out of scope for this pass, same boundary `Ref<M>`
    /// already draws.
    ///
    /// Defaults to `AssociationOwner::Default`/`AssociationStorage::Column`; set the
    /// returned `AssociationDecl`'s public fields directly to override.
    pub fn association<A: AssociationMarker>(&mut self) -> &mut AssociationDecl {
        self.decl.associations.push(AssociationDecl {
            name: A::NAME.to_string(),
            target: A::To::qualified_name(),
            association_type: A::ASSOCIATION_TYPE,
            owner: AssociationOwner::Default,
            storage: AssociationStorage::Column,
            documentation: String::new(),
        });
        self.decl.associations.last_mut().expect("just pushed")
    }

    fn push_attribute(
        &mut self,
        name: impl Into<String>,
        attribute_type: AttributeType,
    ) -> &mut AttributeDecl {
        self.decl
            .attributes
            .push(AttributeDecl::new(name, attribute_type));
        self.decl.attributes.last_mut().expect("just pushed")
    }
}
