//! Renders a [`Manifest`](crate::manifest::Manifest) into Rust source: one
//! `pub mod` per Mendix module, one zero-sized `pub struct` per entity
//! implementing `mxrs_ir::EntityMarker`, one zero-sized `pub struct` per
//! attribute implementing `mxrs_ir::AttributeMarker<Entity = Entity>`, one
//! zero-sized `pub struct` per association implementing
//! `mxrs_ir::AssociationMarker<From = Entity, To = Target>`, and one
//! zero-sized `pub struct` per microflow implementing
//! `mxrs_ir::MicroflowMarker`, and one per nanoflow implementing
//! `mxrs_ir::NanoflowMarker`. Attribute and association markers are
//! flat-named `Entity_Name` rather than nested in a same-named submodule (a
//! type and a module can't share a name) — `Entity`'s own attribute names
//! and association names share that flat namespace, so a manifest with e.g.
//! both an attribute and an association named `Total` on the same entity is
//! a [`TypegenError::MarkerNameCollision`] at generation time, not a
//! confusing rustc "duplicate definition" error. Microflow markers are
//! module-scoped (not entity-scoped, since a microflow doesn't belong to an
//! entity) and named verbatim, sharing the module's own flat item namespace
//! with its entities — a microflow named the same as an entity in the same
//! module is a [`TypegenError::ModuleItemNameCollision`], for the same
//! reason.
//!
//! An association's target is validated against every entity declared
//! *anywhere* in the manifest (not just the current module) before any code
//! is emitted — a two-pass generation: collect every module's entities into
//! a project-wide `known_entities` set first, then emit. A same-module
//! target's `To` is the bare sibling-item path; a cross-module target's is
//! `super::TargetModule::TargetEntity` (every generated `pub mod` is a
//! sibling at the output's top level, so reaching another one from inside
//! `mod Sales { ... }` needs `super::` first) — Rust doesn't require items
//! to be declared before they're referenced, so it doesn't matter that
//! `CRM`'s module text might appear later in the generated file than the
//! `Sales.Order_Account` association referencing it.

use std::collections::HashSet;
use std::fmt::Write as _;

use crate::TypegenError;
use crate::manifest::{AssociationManifest, EntityManifest, Manifest, ModuleManifest};

pub fn generate(manifest: &Manifest) -> Result<String, TypegenError> {
    let mut known_entities: HashSet<String> = HashSet::new();
    for module in &manifest.modules {
        for entity in &module.entities {
            known_entities.insert(format!("{}.{}", module.name, entity.name));
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by mxrs-typegen — do not edit by hand.\n\n");

    let mut seen_modules: HashSet<&str> = HashSet::new();
    for module in &manifest.modules {
        let module_ident = valid_ident(&module.name, "module name")?;
        if !seen_modules.insert(module.name.as_str()) {
            return Err(TypegenError::DuplicateModule(module.name.clone()));
        }

        // An outer attribute per module (not one `#![allow(...)]` header
        // for the whole file): the generated source is often `include!()`d
        // mid-file rather than used as a standalone crate root or module
        // file, and an inner attribute is only legal at the very start of
        // whatever item contains it — see mxrs-macros' typegen_integration
        // test, which caught this the first time it exercised `include!()`
        // at a non-crate-root position.
        out.push_str("#[allow(non_camel_case_types, non_snake_case, dead_code)]\n");
        writeln!(out, "pub mod {module_ident} {{").unwrap();
        // Entities and microflows are both top-level items in this same
        // `pub mod`, so their names share one flat namespace — tracked
        // together the same way attribute/association names share an
        // entity's flat namespace below.
        let mut seen_module_items: HashSet<&str> = HashSet::new();
        for entity in &module.entities {
            let entity_ident = valid_ident(&entity.name, "entity name")?;
            if !seen_module_items.insert(entity.name.as_str()) {
                return Err(TypegenError::DuplicateEntity(
                    module.name.clone(),
                    entity.name.clone(),
                ));
            }

            writeln!(out, "    pub struct {entity_ident};").unwrap();
            writeln!(out, "    impl mxrs_ir::EntityMarker for {entity_ident} {{").unwrap();
            writeln!(
                out,
                "        const MODULE: &'static str = {:?};",
                module.name
            )
            .unwrap();
            writeln!(out, "        const NAME: &'static str = {:?};", entity.name).unwrap();
            out.push_str("    }\n");

            // Attribute and association markers share one flat namespace
            // (both are `Entity_Name`), so collisions are tracked together.
            let mut seen_markers: HashSet<&str> = HashSet::new();
            for attribute in &entity.attributes {
                let attr_ident = valid_ident(attribute, "attribute name")?;
                if !seen_markers.insert(attribute.as_str()) {
                    return Err(TypegenError::DuplicateAttribute(
                        module.name.clone(),
                        entity.name.clone(),
                        attribute.clone(),
                    ));
                }

                let marker_ident = format!("{entity_ident}_{attr_ident}");
                writeln!(out, "    pub struct {marker_ident};").unwrap();
                writeln!(
                    out,
                    "    impl mxrs_ir::AttributeMarker for {marker_ident} {{"
                )
                .unwrap();
                writeln!(out, "        type Entity = {entity_ident};").unwrap();
                writeln!(out, "        const NAME: &'static str = {attribute:?};").unwrap();
                out.push_str("    }\n");
            }

            for association in &entity.associations {
                emit_association(
                    &mut out,
                    module,
                    entity,
                    &entity_ident,
                    association,
                    &known_entities,
                    &mut seen_markers,
                )?;
            }
        }

        let mut seen_microflows: HashSet<&str> = HashSet::new();
        for microflow in &module.microflows {
            let microflow_ident = valid_ident(microflow, "microflow name")?;
            if !seen_microflows.insert(microflow.as_str()) {
                return Err(TypegenError::DuplicateMicroflow(
                    module.name.clone(),
                    microflow.clone(),
                ));
            }
            if !seen_module_items.insert(microflow.as_str()) {
                return Err(TypegenError::ModuleItemNameCollision(
                    module.name.clone(),
                    microflow.clone(),
                ));
            }

            writeln!(out, "    pub struct {microflow_ident};").unwrap();
            writeln!(
                out,
                "    impl mxrs_ir::MicroflowMarker for {microflow_ident} {{"
            )
            .unwrap();
            writeln!(
                out,
                "        const MODULE: &'static str = {:?};",
                module.name
            )
            .unwrap();
            writeln!(out, "        const NAME: &'static str = {microflow:?};").unwrap();
            out.push_str("    }\n");
        }

        let mut seen_nanoflows: HashSet<&str> = HashSet::new();
        for nanoflow in &module.nanoflows {
            let nanoflow_ident = valid_ident(nanoflow, "nanoflow name")?;
            if !seen_nanoflows.insert(nanoflow.as_str()) {
                return Err(TypegenError::DuplicateNanoflow(
                    module.name.clone(),
                    nanoflow.clone(),
                ));
            }
            if !seen_module_items.insert(nanoflow.as_str()) {
                return Err(TypegenError::ModuleItemNameCollision(
                    module.name.clone(),
                    nanoflow.clone(),
                ));
            }

            writeln!(out, "    pub struct {nanoflow_ident};").unwrap();
            writeln!(
                out,
                "    impl mxrs_ir::NanoflowMarker for {nanoflow_ident} {{"
            )
            .unwrap();
            writeln!(
                out,
                "        const MODULE: &'static str = {:?};",
                module.name
            )
            .unwrap();
            writeln!(out, "        const NAME: &'static str = {nanoflow:?};").unwrap();
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }

    Ok(out)
}

#[allow(clippy::too_many_arguments)]
fn emit_association<'a>(
    out: &mut String,
    module: &ModuleManifest,
    entity: &EntityManifest,
    entity_ident: &str,
    association: &'a AssociationManifest,
    known_entities: &HashSet<String>,
    seen_markers: &mut HashSet<&'a str>,
) -> Result<(), TypegenError> {
    let assoc_ident = valid_ident(&association.name, "association name")?;
    if !seen_markers.insert(association.name.as_str()) {
        return Err(
            if entity.attributes.iter().any(|a| a == &association.name) {
                TypegenError::MarkerNameCollision(
                    module.name.clone(),
                    entity.name.clone(),
                    association.name.clone(),
                )
            } else {
                TypegenError::DuplicateAssociation(
                    module.name.clone(),
                    entity.name.clone(),
                    association.name.clone(),
                )
            },
        );
    }

    let (target_module, target_name) = split_target(&association.target, &module.name);
    let qualified_target = format!("{target_module}.{target_name}");
    if !known_entities.contains(&qualified_target) {
        return Err(TypegenError::UnknownAssociationTarget(
            module.name.clone(),
            entity.name.clone(),
            association.name.clone(),
            qualified_target,
        ));
    }
    let target_entity_ident = valid_ident(target_name, "association target entity name")?;
    let target_path = if target_module == module.name {
        target_entity_ident
    } else {
        let target_module_ident = valid_ident(target_module, "association target module name")?;
        format!("super::{target_module_ident}::{target_entity_ident}")
    };

    let association_type_variant = match association.association_type.as_str() {
        "Reference" | "ReferenceSet" => association.association_type.as_str(),
        other => {
            return Err(TypegenError::UnknownAssociationType(
                module.name.clone(),
                entity.name.clone(),
                association.name.clone(),
                other.to_string(),
            ));
        }
    };

    let marker_ident = format!("{entity_ident}_{assoc_ident}");
    writeln!(out, "    pub struct {marker_ident};").unwrap();
    writeln!(
        out,
        "    impl mxrs_ir::AssociationMarker for {marker_ident} {{"
    )
    .unwrap();
    writeln!(out, "        type From = {entity_ident};").unwrap();
    writeln!(out, "        type To = {target_path};").unwrap();
    writeln!(
        out,
        "        const NAME: &'static str = {:?};",
        association.name
    )
    .unwrap();
    writeln!(
        out,
        "        const ASSOCIATION_TYPE: mxrs_ir::AssociationType = mxrs_ir::AssociationType::{association_type_variant};"
    )
    .unwrap();
    out.push_str("    }\n");
    Ok(())
}

/// Splits a manifest association `target` into `(module, entity)` — a
/// dotted `"Module.Entity"` target names a cross-module entity, otherwise
/// the target is resolved against `default_module`. Self-contained rather
/// than shared with `mxrs-writer::domain`'s identical-in-spirit
/// `association_target` helper: this crate deliberately doesn't depend on
/// `mxrs-writer` (different layer, different job — this validates a
/// manifest at generation time, that resolves a `ProjectDecl` at write
/// time), and the logic is small enough that duplicating it is cheaper than
/// introducing a cross-crate dependency just to share five lines.
fn split_target<'a>(target: &'a str, default_module: &'a str) -> (&'a str, &'a str) {
    match target.split_once('.') {
        Some((module, name)) => (module, name),
        None => (default_module, target),
    }
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

/// Validates `name` is usable verbatim as a Rust identifier — Mendix names
/// are conventionally already PascalCase/no-symbols, so this is a fail-fast
/// check (a clear manifest error) rather than a name-mangling scheme; a
/// name that needs mangling is a signal the manifest itself is wrong.
fn valid_ident(name: &str, context: &str) -> Result<String, TypegenError> {
    let mut chars = name.chars();
    let starts_ok = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    let rest_ok = chars.all(|c| c.is_ascii_alphanumeric() || c == '_');
    if !starts_ok || !rest_ok || name.is_empty() {
        return Err(TypegenError::InvalidIdentifier(
            name.to_string(),
            context.to_string(),
        ));
    }
    if RUST_KEYWORDS.contains(&name) {
        return Err(TypegenError::InvalidIdentifier(
            name.to_string(),
            context.to_string(),
        ));
    }
    Ok(name.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{EntityManifest, ModuleManifest};

    fn sample() -> Manifest {
        Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![
                    EntityManifest {
                        name: "Order".into(),
                        attributes: vec!["Number".into(), "Total".into()],
                        ..Default::default()
                    },
                    EntityManifest {
                        name: "Customer".into(),
                        attributes: vec!["Name".into()],
                        ..Default::default()
                    },
                ],
                ..Default::default()
            }],
        }
    }

    #[test]
    fn generates_a_struct_and_entity_marker_impl_per_entity() {
        let out = generate(&sample()).unwrap();
        assert!(out.contains("pub mod Sales"));
        assert!(out.contains("pub struct Order;"));
        assert!(out.contains("impl mxrs_ir::EntityMarker for Order"));
        assert!(out.contains(r#"const MODULE: &'static str = "Sales";"#));
        assert!(out.contains(r#"const NAME: &'static str = "Order";"#));
    }

    #[test]
    fn generates_a_flat_named_attribute_marker_per_attribute() {
        let out = generate(&sample()).unwrap();
        assert!(out.contains("pub struct Order_Number;"));
        assert!(out.contains("impl mxrs_ir::AttributeMarker for Order_Number"));
        assert!(out.contains("type Entity = Order;"));
    }

    #[test]
    fn rejects_a_module_name_that_is_not_a_valid_identifier() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales-Team".into(),
                entities: vec![],
                ..Default::default()
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(err, TypegenError::InvalidIdentifier(name, _) if name == "Sales-Team"));
    }

    #[test]
    fn rejects_a_rust_keyword_as_an_entity_name() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![EntityManifest {
                    name: "type".into(),
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(err, TypegenError::InvalidIdentifier(name, _) if name == "type"));
    }

    #[test]
    fn generates_a_struct_and_microflow_marker_impl_per_microflow() {
        let mut manifest = sample();
        manifest.modules[0].microflows = vec!["ACT_Notify".into()];
        let out = generate(&manifest).unwrap();
        assert!(out.contains("pub struct ACT_Notify;"));
        assert!(out.contains("impl mxrs_ir::MicroflowMarker for ACT_Notify"));
        assert!(out.contains(r#"const MODULE: &'static str = "Sales";"#));
        assert!(out.contains(r#"const NAME: &'static str = "ACT_Notify";"#));
    }

    #[test]
    fn rejects_a_duplicate_microflow_name_within_a_module() {
        let mut manifest = sample();
        manifest.modules[0].microflows = vec!["ACT_Notify".into(), "ACT_Notify".into()];
        let err = generate(&manifest).unwrap_err();
        assert!(
            matches!(err, TypegenError::DuplicateMicroflow(module, name) if module == "Sales" && name == "ACT_Notify")
        );
    }

    #[test]
    fn rejects_a_microflow_name_colliding_with_an_entity_name_in_the_same_module() {
        let mut manifest = sample();
        manifest.modules[0].microflows = vec!["Order".into()];
        let err = generate(&manifest).unwrap_err();
        assert!(
            matches!(err, TypegenError::ModuleItemNameCollision(module, name) if module == "Sales" && name == "Order")
        );
    }

    #[test]
    fn generates_a_struct_and_nanoflow_marker_impl_per_nanoflow() {
        let mut manifest = sample();
        manifest.modules[0].nanoflows = vec!["NF_Validate".into()];
        let out = generate(&manifest).unwrap();
        assert!(out.contains("pub struct NF_Validate;"));
        assert!(out.contains("impl mxrs_ir::NanoflowMarker for NF_Validate"));
        assert!(out.contains(r#"const NAME: &'static str = "NF_Validate";"#));
    }

    #[test]
    fn rejects_duplicate_or_colliding_nanoflow_names() {
        let mut duplicate = sample();
        duplicate.modules[0].nanoflows = vec!["NF_Validate".into(), "NF_Validate".into()];
        assert!(matches!(
            generate(&duplicate).unwrap_err(),
            TypegenError::DuplicateNanoflow(module, name)
                if module == "Sales" && name == "NF_Validate"
        ));

        let mut colliding = sample();
        colliding.modules[0].microflows = vec!["Run".into()];
        colliding.modules[0].nanoflows = vec!["Run".into()];
        assert!(matches!(
            generate(&colliding).unwrap_err(),
            TypegenError::ModuleItemNameCollision(module, name)
                if module == "Sales" && name == "Run"
        ));
    }

    #[test]
    fn rejects_a_duplicate_entity_name_within_a_module() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![
                    EntityManifest {
                        name: "Order".into(),
                        ..Default::default()
                    },
                    EntityManifest {
                        name: "Order".into(),
                        ..Default::default()
                    },
                ],
                ..Default::default()
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(
            matches!(err, TypegenError::DuplicateEntity(module, entity) if module == "Sales" && entity == "Order")
        );
    }

    #[test]
    fn rejects_a_duplicate_attribute_name_within_an_entity() {
        let manifest = Manifest {
            modules: vec![ModuleManifest {
                name: "Sales".into(),
                entities: vec![EntityManifest {
                    name: "Order".into(),
                    attributes: vec!["Number".into(), "Number".into()],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::DuplicateAttribute(module, entity, attribute)
                if module == "Sales" && entity == "Order" && attribute == "Number"
        ));
    }

    fn manifest_with_association(target: &str) -> Manifest {
        Manifest {
            modules: vec![
                ModuleManifest {
                    name: "Sales".into(),
                    entities: vec![
                        EntityManifest {
                            name: "Order".into(),
                            associations: vec![AssociationManifest {
                                name: "Order_Customer".into(),
                                target: target.into(),
                                association_type: "Reference".into(),
                            }],
                            ..Default::default()
                        },
                        EntityManifest {
                            name: "Customer".into(),
                            ..Default::default()
                        },
                    ],
                    ..Default::default()
                },
                ModuleManifest {
                    name: "CRM".into(),
                    entities: vec![EntityManifest {
                        name: "Account".into(),
                        ..Default::default()
                    }],
                    ..Default::default()
                },
            ],
        }
    }

    #[test]
    fn generates_an_association_marker_for_a_same_module_target() {
        let out = generate(&manifest_with_association("Customer")).unwrap();
        assert!(out.contains("pub struct Order_Order_Customer;"));
        assert!(out.contains("impl mxrs_ir::AssociationMarker for Order_Order_Customer"));
        assert!(out.contains("type From = Order;"));
        assert!(out.contains("type To = Customer;"));
        assert!(out.contains(
            "const ASSOCIATION_TYPE: mxrs_ir::AssociationType = mxrs_ir::AssociationType::Reference;"
        ));
    }

    #[test]
    fn generates_an_association_marker_for_a_cross_module_target() {
        let out = generate(&manifest_with_association("CRM.Account")).unwrap();
        assert!(out.contains("type To = super::CRM::Account;"));
    }

    #[test]
    fn rejects_an_association_targeting_an_entity_absent_from_the_manifest() {
        let err = generate(&manifest_with_association("Ghost")).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::UnknownAssociationTarget(module, entity, name, target)
                if module == "Sales" && entity == "Order" && name == "Order_Customer" && target == "Sales.Ghost"
        ));
    }

    #[test]
    fn rejects_an_association_with_an_unknown_type() {
        let mut manifest = manifest_with_association("Customer");
        manifest.modules[0].entities[0].associations[0].association_type = "Bogus".into();
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::UnknownAssociationType(module, entity, name, ty)
                if module == "Sales" && entity == "Order" && name == "Order_Customer" && ty == "Bogus"
        ));
    }

    #[test]
    fn rejects_a_duplicate_association_name_within_an_entity() {
        let mut manifest = manifest_with_association("Customer");
        let dup = manifest.modules[0].entities[0].associations[0].clone();
        manifest.modules[0].entities[0].associations.push(dup);
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::DuplicateAssociation(module, entity, name)
                if module == "Sales" && entity == "Order" && name == "Order_Customer"
        ));
    }

    #[test]
    fn rejects_an_attribute_and_association_sharing_a_name_on_the_same_entity() {
        let mut manifest = manifest_with_association("Customer");
        manifest.modules[0].entities[0]
            .attributes
            .push("Order_Customer".into());
        let err = generate(&manifest).unwrap_err();
        assert!(matches!(
            err,
            TypegenError::MarkerNameCollision(module, entity, name)
                if module == "Sales" && entity == "Order" && name == "Order_Customer"
        ));
    }
}
